### ISSUE TITLE
`teleport_function` example doesn't seem to work

### ISSUE THREAD

**Issue by campbellr** [tomerfiliba/rpyc#155]
Using the latest version of RPyC (3.3), the `teleport_function` method seems to be broken.

Using the example from the docs (http://rpyc.readthedocs.org/en/latest/api/utils_classic.html#rpyc.utils.classic.teleport_function):

``` python
from rpyc.utils.zerodeploy import DeployedServer
from rpyc.utils.classic import teleport_function
from plumbum.machines.ssh_machine import SshMachine

if __name__ == '__main__':
    machine = SshMachine('localhost')
    server = DeployedServer(machine)
    conn = server.classic_connect()

    def f(x, y):
        import os
        return (os.getpid() + y) * x

    r_f = teleport_function(conn, f)

    print f(1, 2)
    print r_f(1, 2)

```

And the error when I run it:

``` console
 $ python teleport_test.py 
17798
Traceback (most recent call last):
  File "teleport_test.py", line 17, in <module>
    print r_f(1, 2)
  File "/localhome/campbr9/.virtualenvs/vats/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/localhome/campbr9/.virtualenvs/vats/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/localhome/campbr9/.virtualenvs/vats/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
ImportError: cannot import name os

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/tmp.XV2H3lS6dw/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/tmp.XV2H3lS6dw/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "teleport_test.py", line 11, in f
ImportError: cannot import name os

```

Am I using this wrong?

**Comment by coldfix** [comment]
Hi, the example works for me.

If it still fails for you, please reopen.
