### ISSUE TITLE
new connection exits on timeout, while it shouldn't

### ISSUE THREAD

**Issue by eplaut** [tomerfiliba/rpyc#162]
Hi,
I'm facing long connection timeout, which I relate to recv() of the header in the very first connection.
the Exception I'm getting is:

```

Traceback (most recent call last):
  File "mycode.py", line 105, in __init__
    self._rpyc = rpyc.classic.connect(address, keepalive=2)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/classic.py", line 68, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/factory.py", line 91, in connect
    return connect_stream(s, service, config)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/factory.py", line 52, in connect_stream
    return connect_channel(Channel(stream), service = service, config = config)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/factory.py", line 41, in connect_channel
    return Connection(service, channel, config = config)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 151, in __init__
    self._init_service()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 154, in _init_service
    self._local_root.on_connect()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/service.py", line 145, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 482, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 446, in sync_request
    self.serve(0.1)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 394, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 352, in _recv
    data = self._channel.recv()
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 50, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py", line 206, in read
    raise EOFError(ex)
EOFError: [Errno 110] Connection timed out
```

in `rpyc/core/stream.py` I see that socket.timeout is continued to next try to read the buffer, but still I'm getting errno.TIMEDOUT (110). looking in the comment "windows just has to be a bitch", I suggest errno.TIMEDOUT should be included in `retry_errnos`

**Comment by coldfix** [comment]
Cleaning out old issues that might be out of date.

If you still have this issue, please reopen and provide a full example, is this connected to localhost or a remote machine, can you otherwise access the remote machine, etc?

Best, Thomas
