### ISSUE TITLE
demos\time client fails

### ISSUE THREAD

**Issue by clach04** [tomerfiliba/rpyc#179]
Checkout of 7599ccfc85e17379aeee530b262c0cc6c0671988, client demo fails to find time service:

    D:\\rpyc\demos\time>client.py
    Traceback (most recent call last):
      File "D:\\rpyc\demos\time\client.py", line 4, in <module>
        c = rpyc.connect_by_service("TIME")
      File "D:\\rpyc\demos\time\rpyc\utils\factory.py", line 211, in connect_by_service
        host, port = discover(service_name, host = host)[0]
      File "D:\\rpyc\demos\time\rpyc\utils\factory.py", line 192, in discover
        raise DiscoveryError("no servers exposing %r were found" % (service_name,))
    rpyc.utils.factory.DiscoveryError: no servers exposing 'TIME' were found

If the server and client is modified to specify a port and client does not use service name, demo works fine:

    from rpyc.utils.server import ThreadedServer
    from time_service import TimeService

    if __name__ == "__main__":
        #s = ThreadedServer(TimeService)
        s = ThreadedServer(TimeService, port=1234)
        s.start()

client:

    import rpyc

    #c = rpyc.connect_by_service("TIME")
    c = rpyc.connect('localhost', 1234)
    print( "server's time is", c.root.get_time())

**Comment by clach04** [comment]
https://github.com/tomerfiliba/rpyc/blob/master/docs/tutorial/tut3.rst mentions registry_server.py - even when this is running TIME look up fails. Out out from registry_server.py :+1: 

    DEBUG:REGSRV/UDP/18811:server started on 0.0.0.0:18811
    DEBUG:REGSRV/UDP/18811:querying for 'TIME'
    DEBUG:REGSRV/UDP/18811:no such service

No register appears to take place.

If this is needed, a one line comment may be appropriate in the client (and server) demo source.

**Comment by clach04** [comment]
See issue #180
