### ISSUE TITLE
Error when remote function concatenates list netref to a list using `+`

### ISSUE THREAD

**Issue by ArnaudCalmettes** [tomerfiliba/rpyc#192]
I have stumbled on this error recently. Here is a minimalistic example:

``` python
class SomeService(rpyc.Service):
    def expose_use_list(self, lst):
        return lst + [4, 5, 6]
```

```
>>> c = rpyc.connect("localhost", 1337, service=SomeService)
>>> c.root.use_list([1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
TypeError: can only concatenate list (not "list") to list

========= Remote Traceback (2) =========
Traceback (most recent call last):
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "./some_service.py", line 11, in exposed_used_list
    return lst + [4, 5, 6]
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 210, in method
    return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
TypeError: can only concatenate list (not "list") to list

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/arnaud/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 547, in _handle_callattr
    return self._handle_getattr(oid, name)(*args, **dict(kwargs))
TypeError: can only concatenate list (not "list") to list
```

Is there something I have done wrong, or any known workaround for this, or is it an actual bug ?

**Comment by GeeF** [comment]
Same here. You can use ``extend()`` as a workaround.
So instead of:
```python
class SomeService(rpyc.Service):
    def expose_use_list(self, lst):
        return lst + [4, 5, 6]
```
do
```python
class SomeService(rpyc.Service):
    def expose_use_list(self, lst):
        lst.extend([4, 5, 6])
        return lst

**Comment by ArnaudCalmettes** [comment]
Hi,

Actually it doesn't solve my specific problem since the + operator is used
in a function of the standard library I am using remotely. However I found
a workaround in the meantime, by hacking into the zerodeploy configuration
to monkey patch the SlaveService with a custom exposed method.

Thanks.
Le 19 mai 2016 15:06, "GeeF" <notifications@github.com> a écrit :

Same here. You can use extend() as a workaround.
So instead of:

class SomeService(rpyc.Service):
    def expose_use_list(self, lst):
        return lst + [4, 5, 6]

do

class SomeService(rpyc.Service):
    def expose_use_list(self, lst):
        lst.extend([4, 5, 6])
        return lst

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/tomerfiliba/rpyc/issues/192#issuecomment-220318105>

**Comment by coldfix** [comment]
Hi,

the problem is that if the client calls `use_list(['foo', 'bar'])` a netref is transmitted to the server, meaning that `list.__add__([4, 5, 6])` will be executed on the client. But in fact, what the client sees is a netref to `[4, 5, 6]`. Now, you can blame python that `list.__add__` does not deal with arbitrary iterables but requires lists only.

To solve the issue, call `use_list(deliver(['foo', 'bar']))` (i.e. pickle+unpickle) on the client, or `obtain(lst)` on the server.

I briefly thought about inheriting the netref from `list` but I believe that's not really feasible, since my experience with deriving from builtin types in python is that they don't really give you full control..
