### ISSUE TITLE
AttributeError: '********' object has no attribute '*******'

### ISSUE THREAD

**Issue by s-nt-s** [tomerfiliba/rpyc#198]
I have this code:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os
import sys
import rpyc
from rpyc.utils.server import ThreadedServer

import MyBot

class XmppService(rpyc.Service):
    def on_connect(self):
        # code that runs when a connection is created
        # (to init the serivce, if needed)
        pass

    def on_disconnect(self):
        # code that runs when the connection has already closed
        # (to finalize the service, if needed)
        pass

    def exposed_send_mensage(self, msg, to=None):
        self.exposed_bot.write_message(msg, to)

    def exposed_login(self):
        self.exposed_bot = MyBot.MyBot()
        self.exposed_bot.run()

if __name__ == "__main__":
    if len(sys.argv)>1:
        if sys.argv[1]=="login":
            c = rpyc.connect("localhost", 18861)
            c.root.login()
        else:
            c = rpyc.connect("localhost", 18861)
            c.root.send_mensage(" ".join(sys.argv[1:]))
    else:
        t = ThreadedServer(XmppService, port = 18861)
        t.start()
```
then:

- I run `python xmppservice.py` and it is ok
- I run `python xmppservice.py login` and it is ok
- I run `python xmppservice.py bla bla bla bla` and then:

```console
$ python xmppservice.py bla bla bla bla
Traceback (most recent call last):
  File "xmppservice.py", line 38, in <module>
    c.root.send_mensage(" ".join(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
AttributeError: 'XmppService' object has no attribute 'exposed_bot'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "xmppservice.py", line 25, in exposed_send_mensage
    self.exposed_bot.write_message(msg, to)
AttributeError: 'XmppService' object has no attribute 'exposed_bot'
```

And in the server side:
```console
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "xmppservice.py", line 25, in exposed_send_mensage
    self.exposed_bot.write_message(msg, to)
AttributeError: 'XmppService' object has no attribute 'exposed_bot'
```

**Comment by strayArch** [comment]
I am experiencing similar issues. I'm having an issue with a nested dictionary as an argument. Say ````data={'a': {'b':'c'}}```, when I try to use ```data.keys()``` it raises an AttributeError and ```allow_all_attrs,allow_public_attrs``` are ```True```.

Here is my log.
```
2016-11-12 00:22:52 INFO:db-service:SIMP: <type 'dict'>  {'origin_user': u'james', u'users': {u'add': {u'bob': u'edit'}}, u'workspacename': u'james@asdf'}
2016-11-12 00:22:52 INFO:db-service:SIMP: <type 'unicode'>  james@asdf
2016-11-12 00:22:52 INFO:db-service:SIMP: <type 'NoneType'>  None
2016-11-12 00:22:52 INFO:db-service:SIMP: <netref class '__builtin__.dict'>  {u'add': {u'bob': u'edit'}}
2016-11-12 00:22:52 INFO:db-service:QQ: <netref class '__builtin__.dict'> {u'add': {u'bob': u'edit'}}
2016-11-12 00:22:52 ERROR:manager:workspaceMod
Traceback (most recent call last):
  File "manager.py", line 1227, in workspaceMod
    uwg.workspacemod(**kwargs)
  File "/usr/local/np-live/nplive_utils/db_service.py", line 687, in workspacemod
    UWG.update_hm(wu_name, users, connection=pipe)#TODO work on improving this call
  File "/usr/local/np-live/nplive_utils/db_service.py", line 457, in update_hm
    if 'add' in data.keys():
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 150, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
AttributeError: cannot access 'keys'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 541, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 504, in _access_attr
    raise AttributeError("cannot access %r" % (name,))
AttributeError: cannot access 'keys'
```
Work around:
- Rather than json.dumps prior to the RPyC call, I simply json.dumps in the exposed method to resolve the issue.

**Comment by aplicacionamedida** [comment]
Hi ,
I am not sure whether this is a bug. It seems that different connections have different namespaces. I tried this code and it works:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os
import sys
import rpyc
from rpyc.utils.server import ThreadedServer

class MyBot(object):
    def run(self):
        print "running..."
        
    def write_message(self, msg, to):
        print "messaget to %s: %s"%(to, msg)

class XmppService(rpyc.Service):
    def on_connect(self):
        # code that runs when a connection is created
        # (to init the serivce, if needed)
        pass

    def on_disconnect(self):
        # code that runs when the connection has already closed
        # (to finalize the service, if needed)
        pass

    def exposed_send_mensage(self, msg, to=None):
        self.exposed_bot.write_message(msg, to)

    def exposed_login(self):
        self.exposed_bot = MyBot()
        self.exposed_bot.run()

if __name__ == "__main__":
    if len(sys.argv)>1:
        c = rpyc.connect("localhost", 18861)
        c.root.login()
        c.root.send_mensage(" ".join(sys.argv[2:]), sys.argv[1])
    else:
        t = ThreadedServer(XmppService, port = 18861)
        t.start()
```
I run this:
```
python xmppservice.py user bla bla bla
```
and I get this result:
```
running...
messaget to user: bla bla bla
```

**Comment by s-nt-s** [comment]
Yes. That works because you do login and send message in the same execution, but what I was searching is a way to send a message using a previous connection. My final goal is to have a bot xmpp always connected as a daemon and that other script can ask it to send messages using the connection already open whiteout needing to do login again.

**Comment by aplicacionamedida** [comment]
You can do something like this:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import os
import sys
import rpyc
from rpyc.utils.server import ThreadedServer

class MyBot(object):
    def run(self):
        print "running..."

    def write_message(self, msg, to):
        print "message to %s: %s"%(to, msg)

class XmppService(rpyc.Service):
    def on_connect(self):
        # code that runs when a connection is created
        # (to init the serivce, if needed)
        pass

    def on_disconnect(self):
        # code that runs when the connection has already closed
        # (to finalize the service, if needed)
        pass

    def exposed_send_mensage(self, msg, to=None):
        bot.write_message(msg, to)

if __name__ == "__main__":
    if len(sys.argv)>1:
        c = rpyc.connect("localhost", 18861)
        c.root.login()
        c.root.send_mensage(" ".join(sys.argv[2:]), sys.argv[1])
    else:
        bot = MyBot()
        bot.run()
        t = ThreadedServer(XmppService, port = 18861)
        t.start()
```

**Comment by aplicacionamedida** [comment]
I think that another possibility is to create a custom service sharing the namespace to all connections.

I have an example in this recipe:
https://code.activestate.com/recipes/580721-tkinter-remote-debugging/

**Comment by s-nt-s** [comment]
with bot as a global variable I get this:

```console
Traceback (most recent call last):
  File "xmppservice2.py", line 32, in <module>
    c.root.send_mensage(" ".join(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
NameError: global name 'bot' is not defined

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "xmppservice2.py", line 23, in exposed_send_mensage
    bot.write_message(msg, to)
NameError: global name 'bot' is not defined
```

MyBot came from https://github.com/s-nt-s/XmppBot and the run method came from https://github.com/s-nt-s/XmppBot/blob/master/xmppbot.py#L155
maybe the problem is run method not finish?

**Comment by coldfix** [comment]
As noted by @aplicacionamedida, this is not a bug. Each connection creates an independent service object. This fact is now documented in the tutorial.

Regarding your last post: Since you didn't show your code, I can only guess you didn't explicitly set `global bot` before setting `bot = ...` in the login method.

**Comment by coldfix** [comment]
Note that in the next release (3.5) it will be possible to share the same service object for multiple connections by passing in a fully constructed service instance as the `service` argument.
