### ISSUE TITLE
Cannot access 'keys' in nested object, allow_all_attrs and allow_public_attrs are true

### ISSUE THREAD

**Issue by strayArch** [tomerfiliba/rpyc#199]
I'm having an issue with a nested dictionary as an argument. As a reduced explanation, say ```data={'users':{'a': {'b':'c'}}```, when I try to use ```data['users'].keys()``` it raises an AttributeError and ```allow_all_attrs,allow_public_attrs``` are ```True```.

Here is my log.
```
2016-11-12 00:22:52 INFO:db-service:SIMP: <type 'dict'>  {'origin_user': u'james', u'users': {u'add': {u'bob': u'edit'}}, u'workspacename': u'james@asdf'}
2016-11-12 00:22:52 INFO:db-service:SIMP: <type 'unicode'>  james@asdf
2016-11-12 00:22:52 INFO:db-service:SIMP: <type 'NoneType'>  None
2016-11-12 00:22:52 INFO:db-service:SIMP: <netref class '__builtin__.dict'>  {u'add': {u'bob': u'edit'}}
2016-11-12 00:22:52 INFO:db-service:QQ: <netref class '__builtin__.dict'> {u'add': {u'bob': u'edit'}}
2016-11-12 00:22:52 ERROR:manager:workspaceMod
Traceback (most recent call last):
  File "manager.py", line 1227, in workspaceMod
    uwg.workspacemod(**kwargs)
  File "/usr/local/np-live/nplive_utils/db_service.py", line 687, in workspacemod
    UWG.update_hm(wu_name, users, connection=pipe)#TODO work on improving this call
  File "/usr/local/np-live/nplive_utils/db_service.py", line 457, in update_hm
    if 'add' in data.keys():
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 150, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
AttributeError: cannot access 'keys'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 541, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 504, in _access_attr
    raise AttributeError("cannot access %r" % (name,))
AttributeError: cannot access 'keys'
```
Work around:
- Rather than json.dumps prior to the RPyC call, I simply json.dumps in the exposed method to resolve the issue.

I'll see if I can create a minimal reproduction, when I get a chance.

**Comment by aplicacionamedida** [comment]
Hi,
I cant reproduce your bug. I tried this:
- First I started the classic server:
```
    python rpyc_classic.py  -m forking
```
- In an interactive python interpreter, I wrote this:
```
>>> import rpyc
>>> c = rpyc.classic.connect("localhost")
>>> c.execute("""a = {'hola': {"vaya":2}}""")
>>> a = c.eval("a")
>>> a["hola"].keys()
['vaya']
>>> a.keys()
['hola']
```

**Comment by strayArch** [comment]
Thank you! I'll see if I can track it down further. The issue very well may be a bug in the code at work, another library, etc.
