### ISSUE TITLE
ThreadPoolServer deadlock

### ISSUE THREAD

**Issue by xBeAsTx** [tomerfiliba/rpyc#203]
Backtrace:

```
...
Thread 30 (Thread 0x7fd1f9ffb700 (LWP 14142)):
#4 Frame 0x7fd30002dcf0, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 227, in _send (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>, _RLock__...(truncated)
    self._sendlock.acquire()
#7 Frame 0x7fd3baac0430, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 234, in _send_request (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>, ...(truncated)
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
#10 Frame 0x7fd32400ba20, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 446, in _async_request (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>,...(truncated)
    seq = self._send_request(handler, args)
#14 Frame 0x7fd2fc02cb90, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 458, in async_request (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>, ...(truncated)
    self._async_request(handler, args, res)
#19 Frame 0x7fd3b002d6d0, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py, line 89, in asyncreq (proxy=<instancemethod at remote 0x7fd378334050>, handler=15, args=(), conn=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owne...(truncated)
    return conn.async_request(handler, oid, *args)
#23 Frame 0x7fd27c02e070, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py, line 125, in __del__ (self=<instancemethod at remote 0x7fd378334050>)
    asyncreq(self, consts.HANDLE_DEL)
#48 Frame 0x7fd3c62af220, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py, line 163, in close (self=<SocketStream at remote 0x7fd3783741a0>)
    self.sock.shutdown(socket.SHUT_RDWR)
#51 Frame 0x7fd3a403a4f0, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py, line 206, in write (self=<SocketStream at remote 0x7fd3783741a0>, data='\x00\x00\x00\x08\x00\x12Qo\x11R\x11Q\x02\n', ex=<error at remote 0x7fd3baab3e88>)
    self.close()
#54 Frame 0x7fd364030650, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py, line 69, in send (self=<Channel at remote 0x7fd3c1c29110>, data='\x12Qo\x11R\x11Q\x02', compressed=0, header='\x00\x00\x00\x08\x00', buf='\x00\x00\x00\x08\x00\x12Qo\x11R\x11Q\x02\n')
    self.stream.write(buf)
#57 Frame 0x7fd3480342d0, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 229, in _send (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>, _RLock__...(truncated)
    self._channel.send(data)
#60 Frame 0x7fd2e80282a0, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 234, in _send_request (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>, ...(truncated)
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
#63 Frame 0x7fd1ec02d7e0, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 446, in _async_request (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>,...(truncated)
    seq = self._send_request(handler, args)
#67 Frame 0x7fd2ec029a90, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py, line 192, in close (self=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owner=None, _RLock__block=<thread.lock at remote 0x7fd3c4c926d0>, _RLock__...(truncated)
    self._async_request(consts.HANDLE_CLOSE)
#71 Frame 0x7fd3c61f9b90, for file /usr/local/lib/python2.7/dist-packages/some_project/thserv.py, line 109, in _drop_connection (self=<ThreadPoolServer(listener=<_socketobject at remote 0x7fd3baab7d70>, auto_register=False, service=<type at remote 0x192b060>, fd_to_conn={5: <Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:44058', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remo...(truncated)
    conn.close()
#74 Frame 0x7fd3c62ab430, for file /usr/local/lib/python2.7/dist-packages/some_project/thserv.py, line 124, in _handle_poll_result (self=<ThreadPoolServer(listener=<_socketobject at remote 0x7fd3baab7d70>, auto_register=False, service=<type at remote 0x192b060>, fd_to_conn={5: <Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:44058', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at r...(truncated)
    self._drop_connection(fd)
#77 Frame 0x7fd3c62ac230, for file /usr/local/lib/python2.7/dist-packages/some_project/thserv.py, line 141, in _poll_inactive_clients (self=<ThreadPoolServer(listener=<_socketobject at remote 0x7fd3baab7d70>, auto_register=False, service=<type at remote 0x192b060>, fd_to_conn={5: <Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:44058', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='PROJAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file a...(truncated)
    self._handle_poll_result(active_clients)
#82 Frame 0x7fd3c62ae050, for file /usr/lib/python2.7/threading.py, line 763, in run (self=<Thread(_Thread__ident=140539819177728, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fd3c6284dd0>, acquire=<built-in method acquire of thread.lock object at remote 0x7fd3c6284dd0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fd3c6284dd0>) at remote 0x7fd3c62a7850>, _Thread__name='PollingThread', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fd3c6284d70>, acquire=<built-in method acquire of thread.lock object at remote 0x7fd3c6284d70>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fd3c6284d70>) at remote 0x7fd3c62a7790>) at remote 0x7fd3c62a7710>, _Thread__stderr=<file at remote 0x7fd3c7ea11e0>, _Thread__target=<instancemethod at remote 0x7fd3c62...(truncated)
    self.__target(*self.__args, **self.__kwargs)
#85 Frame 0x7fd1e8000910, for file /usr/lib/python2.7/threading.py, line 810, in __bootstrap_inner (self=<Thread(_Thread__ident=140539819177728, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fd3c6284dd0>, acquire=<built-in method acquire of thread.lock object at remote 0x7fd3c6284dd0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fd3c6284dd0>) at remote 0x7fd3c62a7850>, _Thread__name='PollingThread', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fd3c6284d70>, acquire=<built-in method acquire of thread.lock object at remote 0x7fd3c6284d70>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fd3c6284d70>) at remote 0x7fd3c62a7790>) at remote 0x7fd3c62a7710>, _Thread__stderr=<file at remote 0x7fd3c7ea11e0>, _Thread__target=<instancemethod at re...(truncated)
    self.run()
#88 Frame 0x7fd3c62a9750, for file /usr/lib/python2.7/threading.py, line 783, in __bootstrap (self=<Thread(_Thread__ident=140539819177728, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fd3c6284dd0>, acquire=<built-in method acquire of thread.lock object at remote 0x7fd3c6284dd0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fd3c6284dd0>) at remote 0x7fd3c62a7850>, _Thread__name='PollingThread', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7fd3c6284d70>, acquire=<built-in method acquire of thread.lock object at remote 0x7fd3c6284d70>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7fd3c6284d70>) at remote 0x7fd3c62a7790>) at remote 0x7fd3c62a7710>, _Thread__stderr=<file at remote 0x7fd3c7ea11e0>, _Thread__target=<instancemethod at remote 0...(truncated)
    self.__bootstrap_inner()
...
```
Do not afraid of custom thserv.py it is fully copy of ThreadPoolServer from rpyc\utils\server.py with little logging changes. I've attached file [thserv.py](https://github.com/tomerfiliba/rpyc/files/674038/thserv.txt) you can compare changes.

So the problem is in broken connection which we want to close by `_drop_connection` method.

We call `close` method of `Connection` class which trying to send some gracefully closing data (rpyc.core.protocol.Connection#close):
```python
    def close(self, _catchall = True):
        """closes the connection, releasing all held resources"""
        if self._closed:
            return
        self._closed = True
        try:
            self._async_request(consts.HANDLE_CLOSE)
        except EOFError:
            pass
        except Exception:
            if not _catchall:
                raise
        finally:
            self._cleanup(_anyway = True)
```

`_async_request` trying to send inside rpyc.core.protocol.Connection:
```python
    def _send(self, msg, seq, args):
        data = brine.dump((msg, seq, args))
        self._sendlock.acquire()
        try:
            self._channel.send(data)
        finally:
            self._sendlock.release()
```
which acquiring `_sendlock`.

And trying write data to inside rpyc.core.stream.SocketStream#write:
```python
    def write(self, data):
        try:
            while data:
                count = self.sock.send(data[:self.MAX_IO_CHUNK])
                data = data[count:]
        except socket.error:
            ex = sys.exc_info()[1]
            self.close()
            raise EOFError(ex)
```
Where exception occures. And we trying to close `Stream` which cause again _send_request which wait `_sendlock` acquring. So deadlock occured.

In original Server class in finnaly block we close real socket (not Connection object): 
https://github.com/tomerfiliba/rpyc/blob/master/rpyc/utils/server.py#L178

Probably it will help avoid this situation. But I'm not sure, need more digging...

**Comment by xBeAsTx** [comment]
Probably was fixed with this pull request https://github.com/tomerfiliba/rpyc/pull/166

**Comment by xBeAsTx** [comment]
Here it is more detailed C-backtrace of Thread 30
```
#19 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7fd3b002d6d0, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py, line 89, in asyncreq (proxy=<instancemethod at remote 0x7fd378334050>, handler=15, args=(), conn=<Connection(_config={'allow_setattr': False, 'safe_attrs': ['__name__', '__doc__', '__len__', '__dict__', '__iter__', '__nonzero__'], 'allow_safe_attrs': True, 'import_custom_exceptions': False, 'connid': '192.168.41.39:48849', 'credentials': None, 'propagate_SystemExit_locally': False, 'include_local_traceback': True, 'instantiate_custom_exceptions': False, 'allow_delattr': False, 'allow_getattr': True, 'allow_pickle': False, 'exposed_prefix': 'exposed_', 'instantiate_oldstyle_exceptions': False, 'allow_public_attrs': True, 'allow_all_attrs': False, 'allow_exposed_attrs': True, 'logger': <Logger(name='VBOXAPISERVICES/18862', parent=<RootLogger(name='root', parent=None, handlers=[<PrRotatingFileHandler(suffix='%Y-%m-%d', stream=<file at remote 0x7fd3c1c6c780>, encoding=None, lock=<_RLock(_Verbose__verbose=False, _RLock__owne...(truncated), throwflag=throwflag@entry=0) at ../Python/ceval.c:2705
#20 0x00000000004a090c in PyEval_EvalCodeEx (co=0x7fd3c61abd30, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, 
    defcount=0, closure=0x0) at ../Python/ceval.c:3252
#21 0x000000000049ab45 in fast_function (nk=0, na=2, n=<optimized out>, pp_stack=0x7fd1f9ff90a0, func=<function at remote 0x7fd3c58eda28>) at ../Python/ceval.c:4116
#22 call_function (oparg=<optimized out>, pp_stack=0x7fd1f9ff90a0) at ../Python/ceval.c:4041
#23 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fd27c02e070, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py, line 125, in __del__ (self=<instancemethod at remote 0x7fd378334050>), 
    throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#24 0x00000000004a1c9a in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=0x0, kwcount=<optimized out>, kws=<optimized out>, argcount=2080563312, args=<optimized out>, 
    locals=0x0, globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3252
#25 function_call.15337 (func=func@entry=<function at remote 0x7fd3c58edc08>, arg=arg@entry=(<instancemethod at remote 0x7fd378334050>,), kw=kw@entry=0x0) at ../Objects/funcobject.c:526
#26 0x00000000004dfe94 in PyObject_Call (kw=0x0, arg=(<instancemethod at remote 0x7fd378334050>,), func=<function at remote 0x7fd3c58edc08>) at ../Objects/abstract.c:2529
#27 instancemethod_call.8802 (func=<function at remote 0x7fd3c58edc08>, func@entry=<instancemethod at remote 0x7fd3c1b14a00>, arg=(<instancemethod at remote 0x7fd378334050>,), arg@entry=(), kw=kw@entry=0x0)
    at ../Objects/classobject.c:2602
#28 0x00000000004f5b99 in PyObject_Call (kw=0x0, arg=(), func=<instancemethod at remote 0x7fd3c1b14a00>) at ../Objects/abstract.c:2529
#29 PyEval_CallObjectWithKeywords (kw=0x0, arg=(), func=<instancemethod at remote 0x7fd3c1b14a00>) at ../Python/ceval.c:3889
#30 slot_tp_del.25586 (self=self@entry=<instancemethod at remote 0x7fd378334050>) at ../Objects/typeobject.c:5758
#31 0x00000000004f6efb in subtype_dealloc.25589 (self=<instancemethod at remote 0x7fd378334050>) at ../Objects/typeobject.c:982
#32 0x00000000004f7031 in clear_slots (self=<optimized out>, type=0x192bfc0) at ../Objects/typeobject.c:864
#33 subtype_dealloc.25589 (self=<_Async at remote 0x7fd3c1c76150>) at ../Objects/typeobject.c:1004
#34 0x000000000055a657 in dict_dealloc.18378 (mp=0x7fd3b82b8c58) at ../Objects/dictobject.c:1010
#35 0x000000000055a52f in dict_dealloc.18378 (mp=0x7fd3c6260398) at ../Objects/dictobject.c:1010
#36 0x00000000004f7a47 in func_dealloc.15345 (op=0x7fd3b8199230) at ../Objects/funcobject.c:455
#37 0x000000000055a8ce in PyDict_Clear (op=0x0) at ../Objects/dictobject.c:916
#38 0x00000000005b5f5a in type_clear.25430 (type=0x7fd2dc038560) at ../Objects/typeobject.c:2761
#39 0x0000000000536a17 in delete_garbage (old=0x9186e0 <generations+96>, collectable=0x7fd1f9ff96d0) at ../Modules/gcmodule.c:820
#40 collect.49008 (generation=<optimized out>) at ../Modules/gcmodule.c:984
#41 0x00000000005373e8 in _PyObject_GC_Malloc (basicsize=31366064) at ../Modules/gcmodule.c:1511
#42 0x000000000053748b in PyType_GenericAlloc (type=0x19552a0, nitems=0) at ../Objects/typeobject.c:761
#43 0x00000000004ac5a0 in BaseException_new.12115 (type=<optimized out>, args=<optimized out>, kwds=<optimized out>) at ../Objects/exceptions.c:34
#44 0x00000000005038d5 in type_call.25495 (type=0x19552a0, args=(107, 'Transport endpoint is not connected'), kwds=0x0) at ../Objects/typeobject.c:729
#45 0x00000000004a424e in PyObject_Call (kw=0x0, arg=(107, 'Transport endpoint is not connected'), func=<type at remote 0x19552a0>) at ../Objects/abstract.c:2529
#46 PyEval_CallObjectWithKeywords (kw=0x0, arg=(107, 'Transport endpoint is not connected'), func=<type at remote 0x19552a0>) at ../Python/ceval.c:3889
#47 PyErr_NormalizeException (exc=exc@entry=0x7fd1f9ff9900, val=val@entry=0x7fd1f9ff9940, tb=tb@entry=0x7fd1f9ff9950) at ../Python/errors.c:192
#48 0x000000000049bcb6 in PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7fd3c62af220, for file /usr/local/lib/python2.7/dist-packages/rpyc/core/stream.py, line 163, in close (self=<SocketStream at remote 0x7fd3783741a0>), throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2919
#49 0x0000000000499ef2 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fd1f9ff9ab0, func=<function at remote 0x7fd3c61911b8>) at ../Python/ceval.c:4106
#50 call_function (oparg=<optimized out>, pp_stack=0x7fd1f9ff9ab0) at ../Python/ceval.c:4041
```

So it's 100% for sure it's garbage collector call. But as for me it's bad fix just disable GC.
