### ISSUE TITLE
AttributeError: 'VoidService' object has no attribute 'exposed_getmodule'

### ISSUE THREAD

**Issue by bigtree6688** [tomerfiliba/rpyc#216]
https://rpyc.readthedocs.io/en/latest/tutorial/tut5.html#events

error log：

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/root/.virtualenvs/rpc/lib/python2.7/site-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/root/.virtualenvs/rpc/lib/python2.7/site-packages/rpyc/core/protocol.py", line 541, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/root/.virtualenvs/rpc/lib/python2.7/site-packages/rpyc/core/protocol.py", line 507, in _access_attr
    return accessor(obj, name, *args)
  File "/root/.virtualenvs/rpc/lib/python2.7/site-packages/rpyc/core/service.py", line 69, in _rpyc_getattr
    return getattr(self, name)
AttributeError: 'VoidService' object has no attribute 'exposed_getmodule'

**Comment by bigtree6688** [comment]
I solved the problem~

`conn = rpyc.connect("localhost", 18871, service=rpyc.SlaveService)`
