### ISSUE TITLE
Python 3.6.1 to Jython 2.7.0 connect() fails

### ISSUE THREAD

**Issue by clach04** [tomerfiliba/rpyc#252]
C:\Python36-32>python.exe
    Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import rpyc
    >>> conn = rpyc.classic.connect("localhost")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\clach04\py\rpyc\rpyc\utils\classic.py", line 70, in connect
        return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
      File "C:\Users\clach04\py\rpyc\rpyc\utils\factory.py", line 93, in connect
        return connect_stream(s, service, config)
      File "C:\Users\clach04\py\rpyc\rpyc\utils\factory.py", line 54, in connect_stream
        return connect_channel(Channel(stream), service=service, config=config)
      File "C:\Users\clach04\py\rpyc\rpyc\utils\factory.py", line 43, in connect_channel
        return service._connect(channel, config)
      File "C:\Users\clach04\py\rpyc\rpyc\core\service.py", line 100, in _connect
        self.on_connect(conn)
      File "C:\Users\clach04\py\rpyc\rpyc\core\service.py", line 195, in on_connect
        self._install(conn, conn.root)
      File "C:\Users\clach04\py\rpyc\rpyc\core\service.py", line 200, in _install
        builtin = modules.builtins if is_py3k else modules.__builtin__
      File "C:\Users\clach04\py\rpyc\rpyc\core\service.py", line 131, in __getattr__
        return self[name]
      File "C:\Users\clach04\py\rpyc\rpyc\core\service.py", line 128, in __getitem__
        self.__cache[name] = self.__getmodule(name)
    TypeError: 'b'instancemethod'' object is not callable

##### Environment

- rpyc version - latest as of commit 994f7e1e112a108e58af4fd8750cdbd67bc29ef9
- python version, Python 3.6.1 for client, Jython 2.7.0 for server
- Windows 10

##### Minimal example

Server:

    jython rpyc_classic.py

Client:

```python
import rpyc

conn = rpyc.classic.connect("localhost")
```

**Comment by coldfix** [comment]
Hi,

unfortunately, communication between py2 and py3 is not supported, see https://rpyc.readthedocs.io/en/latest/install.html#cross-interpreter-compatibility

Also note that jython is currently not well supported. There is at least one serious issue see #229. I believe this issue should be fixable, but I lack the time to investigate atm.

Best, Thomas
