### ISSUE TITLE
EOFerror stream has been closed

### ISSUE THREAD

**Issue by spacerainbow000** [tomerfiliba/rpyc#258]
pretty new to python so sorry if this bug is dumb. I wrote a program that starts an arbitrary job from a set of python files from a directory - try_start_job is called with a job object, which has a first-class reference to the behavior to run. a new thread is spawned running an executor method, which calls the function to do the job along with some parameters from the job object. this works fine when the try_start_job method is called from within the same file it's defined, but when I try to execute the call to try_start_job over rpyc (trying to make a client-service-type-structure) I get the following error:

```
Exception in thread ping:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/floodgate/libs/executor.py", line 18, in executor
    for _ in range(job.cycles):
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/netref.py", line 151, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 519, in sync_request
    self.sync_recv_and_dispatch(timeout, True)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 414, in sync_recv_and_dispatch
    data = self._recv(timeout, wait_for_lock = False)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/protocol.py", line 387, in _recv
    if self._channel.poll(timeout):
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/stream.py", line 40, in poll
    p.register(self.fileno(), "r")
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/stream.py", line 201, in fileno
    return self.sock.fileno()
  File "/usr/local/lib/python3.5/dist-packages/rpyc/core/stream.py", line 89, in fileno
    raise EOFError("stream has been closed")
EOFError: stream has been closed
```
(ping is the name of the thread - the test job just writes a line to stdout)
I call the function from the 'client' like this:

```
import rpyc
conn = rpyc.connect("localhost", 18861, config={"allow_all_attrs": True})
service = conn.root
r = rpyc.async(service.try_start_job)
res = r(testjob)
print(res.value)
```
what am I doing wrong?

rpyc 3.4.4
python 3.5.2
Ubuntu 16.04.3 LTS

**Comment by coldfix** [comment]
Hey,

it's hard to say anything definitive without a full example.

Do you get this error in the server or client process?

With current rpyc, you always have to keep a (non-cyclic) reference to the `conn` object. This is the case in your example client posted here. However, if your real client forgets about `conn` some time after assigning `service`, it can very likely lead to an EOFError like this.

It could also be an error in rpyc (there are some other long standing EOF errors, often with pypy).

Did you install rpyc from github or pypi? If from github, I have a suspicion about a problem that I have newly introduced. Will take me a few days to get back to this, though.

**Comment by spacerainbow000** [comment]
I installed rpyc via pip. I'll include as much example code as I can
service:
```
#!/usr/bin/env python3
import rpyc
import requests
from jq import jq
import sys
import os
from threading import Thread
import time

sys.path.append('/floodgate/libs/')
import auth
import job
from executor import executor
import simulations
from simulations import *

#get global configurations
import configparser
parser = configparser.RawConfigParser()
config_path = r'/floodgate/configs/config'
parser.read(config_path)
gconf = dict()
gconf['target'] = parser.get('DEFAULT', 'target')

authmanager = auth

class floodgate_service(rpyc.Service):
    def on_connect(self):
        print ("floodgate RPC initiated")
        pass
    def on_disconnect(self):
        pass
    def exposed_ping(self):
        return ping.execute()
    def exposed_print_active_users(self):
        auth.print_active_users()
    def exposed_print_active_sessions(self):
        auth.print_active_sessions()
    def exposed_try_login_user(self, username, password):
        auth.create_session_if_not_exists(username, password)
    def exposed_try_logout_user(self, username):
        auth.destroy_session(username)
    def exposed_get_session(self, username):
        return auth.get_session(username)
    #spawn listener thread to check for jobs to clean up every 10 seconds
    def job_reaper():
        try:
            for t in floodgate_jobs:
                if floodgate_jobs[t].halted == True:
                    del floodgate_jobs[t]
            threading.Timer(10, job_reaper).start()
        except NameError:
            #no jobs triggered yet
            pass
    job_reaper()
    def exposed_try_start_job(self, job):
        thread_spawn = Thread(target = executor, name = job.tag, args = (job,))
        thread_spawn.start()
        self.floodgate_jobs[thread_spawn.ident] = job
    def exposed_try_stop_job(self, tag):
        #check for tag and thread ID in same check
        for t in floodgate_jobs:
            if t == tag or floodgate_jobs[t].tag == tag:
                floodgate_jobs[t].halted = True
    def __init__(self, *args):
        self.floodgate_jobs = dict()
        print ("started")
if __name__ == "__main__":
    from rpyc.utils.server import ThreadedServer
    t = ThreadedServer(floodgate_service, port=18861)
    t.start()
```
client:
```
#!/usr/bin/env python3
import sys
import os
import configparser

sys.path.append('/floodgate/libs/')
import auth
import job
import executor
import simulations
from simulations import *

import time

def package_session(session):
    sessions = dict()
    sessions[session['username']] = session
    return sessions

#get global configurations
parser = configparser.RawConfigParser()
config_path = r'/floodgate/configs/config'
parser.read(config_path)
gconf = dict()
gconf['target'] = parser.get('DEFAULT', 'target')

#connect to service
import rpyc
conn = rpyc.connect("localhost", 18861, config={"allow_all_attrs": True}) #establish connection
service = conn.root #define request service
#bgrunner = rpyc.BgServingThread(conn) #background process execution - not sure what this is just yet

#test
service.try_login_user("user", "password")
testjob = job.floodgate_job(behavior = ping.execute, sessions = package_session(service.get_session('user')), cycles = 3, delay = 5, tag = 'ping')
print (testjob.behavior)
print (testjob.sessions)
print (testjob.tag)
print (testjob.cycles)
print (testjob.delay)
print (testjob.halted)
print ("trying to start job")
r = rpyc.async(service.try_start_job)
res = r(testjob)
#res.wait()
print(res.value)
```
executor:
```
#!/usr/bin/env python3
import sys
import os
import time

sys.path.append('/floodgate/libs')
import auth
import job
import simulations
from simulations import *

def executor(job):
    if job.cycles == -1:
        while job.halted == False:
            job.behavior(job.sessions)
            time.sleep(job.delay)
    else:
        for _ in range(job.cycles):
            if job.halted == False:
                job.behavior(job.sessions)
                time.sleep(job.delay)
            else:
                return
    #clean up
    job.halt()
```
job.py:
```
#!/usr/bin/env python3
import sys
import os

import auth
import simulations
from simulations import *

class floodgate_job:
    def __init__(self, behavior, sessions, tag, cycles = 1, delay = 0):
        self.behavior = behavior
        self.sessions = sessions
        self.tag = tag
        self.cycles = cycles
        self.delay = delay
        self.halted = False
    def halt(*args):
        halted = True
```
ping:
```
#!/usr/bin/env python3
import sys
import requests

sys.path.append('/floodgate/libs/')
import auth

def execute(sessions):
    print("it works!", flush=True)

def __init__():
    pass
```
haven't included auth.py cuz it doesn't seem to be relevant and has app-specific code I would rather not post

**Comment by spacerainbow000** [comment]
if you prefer, i could reduce that to something more minimal that still repro's the issue?

**Comment by coldfix** [comment]
Hi, yeah thanks if that's possible. Also, please include everything needed to run, so I can run and analyze it locally. Sorry for not replying earlier.

Best, Thomas

**Comment by spacerainbow000** [comment]
OK I think I cut my scripts down to close to the minimum complexity required to reproduce:

test_service.py:
```
#!/usr/bin/env python3
import rpyc
import requests
import sys
import os
from threading import Thread
import time

sys.path.append('/floodgate/rpyc_dev/')
import ping

class test_service(rpyc.Service):
    def on_connect(self):
        pass
    def on_disconnect(self):
        pass

    def job_reaper():
        try:
            for t in test_jobs:
                if test_jobs[t].halted == True:
                    del test_jobs[t]
            threading.Timer(10, job_reaper).start()
        except NameError:
            #no jobs triggered yet
            pass
    job_reaper()
    def exposed_try_start_job(self, job):
        thread_spawn = Thread(target = executor, name = job.tag, args = (job,))
        thread_spawn.start()
        self.test_jobs[thread_spawn.ident] = job
    def exposed_try_stop_job(self, tag):
        for t in test_jobs:
            if t == tag or test_jobs[t].tag == tag:
                test_jobs[t].halted = True

    def __init__(self, *args):
        self.test_jobs = dict()

class test_job:
    def __init__(self, behavior, data, tag, cycles):
        self.behavior = behavior
        self.data = data
        self.tag = tag
        self.cycles = cycles
        self.halted = False
    def halt(*args):
        halted = True

def executor(job):
    if job.cycles == -1:
        while job.halted == False:
            job.behavior(job.data)
    else:
        for _ in range(job.cycles):
            if job.halted == False:
                job.behavior(job.data)
            else:
                return
    #clean up
    job.halt()

if __name__ == "__main__":
    from rpyc.utils.server import ThreadedServer
    t = ThreadedServer(test_service, port=18861)
    t.start()
```
test_client.py:
```
#!/usr/bin/env python3
import sys
sys.path.append('/floodgate/rpyc_dev/')
import ping
import test_service
import rpyc
conn = rpyc.connect("localhost", 18861, config={"allow_all_attrs": True}) #establish connection
service = conn.root #define request service
testjob = test_service.test_job(behavior = ping.execute, data = "test", cycles = 3, tag = 'ping')
r = rpyc.async(service.try_start_job)
res = r(testjob)
#res.wait()
print(res.value)
```
ping.py:
```
#!/usr/bin/env python3
import sys
import requests

def execute(data):
    print("service is alive", flush=True)

def __init__():
    pass
```
the appended path is specific to my environment so change the sys.append line to point to the filesystem path where the files are kept - put them all in one directory, do `python test_service &` then `python test_client`.

**Comment by coldfix** [comment]
Great, thanks! I will check it out until the weekend.

**Comment by coldfix** [comment]
Hi, and sorry for the delay.

Your code contains multiple errors, many of them related to a misunderstanding how methods and access to member variables works in python. (Are you coming from C++/javaesque programming language?)

E.g. 

```python
    def job_reaper():
        try:
            for t in test_jobs:
                if test_jobs[t].halted == True:
                    del test_jobs[t]
            threading.Timer(10, job_reaper).start()
        except NameError:
            #no jobs triggered yet
            pass
```

is utterly broken, ad should probably read something like:


```python

    def job_reaper(self):
            for t in list(self.test_jobs):
                if self.test_jobs[t].halted:
                    del self.test_jobs[t]
            threading.Timer(10, self.job_reaper).start()
```

other methods are affected as well.

Please fix all programming errors first, before we try to find if there is an issue with rpyc itself.

**Comment by spacerainbow000** [comment]
this is the first python project I've ever done coming from Java. I will try to fix the problem you mentioned and whatever else is problematic, but I think it's important to establish what an 'error' really is. to me an error is 'the compiler/interpreter didn't like my program and spit out "X" instead of running the program/getting to step "Y"'. I fixed all those errors of that nature, in that when I take the code from the client and the code from the service and put them in the same file then have the client make the method calls to service components directly instead of via rpyc, not only do I not get any errors, I also get the results I want. when I change the project to do those same function calls over rpyc, I get an 'error' of the kind I described earlier. based on that my first inclination is to believe that rpyc is the source of that error. If you think that the problem comes from the code and not from rpyc, then I believe you and want to fix it, but you're going to have to be more specific than 'it has errors' because that doesn't mean to me what it means to you.

**Comment by coldfix** [comment]
> to me an error is 'the compiler/interpreter didn't like my program and spit out "X" instead of running the program/getting to step "Y"'

I will say that I'm certain your code doesn't do what you intended it to do, with or without rpyc. That, to me is an 
> but you're going to have to be more specific than 'it has errors'

I was pretty specific.

**Comment by spacerainbow000** [comment]
'bug' is a lot more workable. I'll try to fix the scope/membership problems
