### ISSUE TITLE
ping raises EOFError("connection closed by peer") instead of PingError 

### ISSUE THREAD

**Issue by szabgab** [tomerfiliba/rpyc#265]
This is the client code I have:

```
import rpyc
import sys
import time

if len(sys.argv) < 2:
   exit("Usage {} SERVER".format(sys.argv[0]))

server = sys.argv[1]

conn = rpyc.classic.connect(server)
rsys = conn.modules.sys
print(rsys.version)

for _ in range(10):
    print("pinging")
    conn.ping()
    time.sleep(3)
    print("after wait")
    time.sleep(3)
    print("after more wait")
```

While it was running I stopped (Ctrl-c) the server. The stack trace I got on the client side is

```
Traceback (most recent call last):
  File "rpyc_ping.py", line 16, in <module>
    conn.ping()
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 233, in ping
    if res.value != data:
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/async.py", line 113, in value
    self.wait()
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/async.py", line 54, in wait
    self._conn.poll(timeout = max(timeout, 0))
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 431, in poll
    return self.sync_recv_and_dispatch(timeout, wait_for_lock=False)
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 414, in sync_recv_and_dispatch
    data = self._recv(timeout, wait_for_lock = False)
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/protocol.py", line 388, in _recv
    data = self._channel.recv()
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/channel.py", line 50, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
  File "/Users/gabor/venv3/lib/python3.6/site-packages/rpyc/core/stream.py", line 226, in read
    raise EOFError("connection closed by peer")
EOFError: connection closed by peer
```
The documentation in http://rpyc.readthedocs.io/en/latest/api/core_protocol.html seems to indicate that it should raise a `PingError`.

Though reading the doc again, might mean that PingError is raised if the other side responds, just not with the correct content.  If the current behavior is expected then maybe the documentation at 
 http://rpyc.readthedocs.io/en/latest/api/core_protocol.html could be amended with something like this:
`If there is no response at all then ping - as every other command - will raise and EOFError: connection closed by peer exception.`

##### Environment

client:
- Python 3.6.3.
- rpyc 3.4.4
- OSX

server
- Python 3.6.3
- rpyc 3.4.4
- Ubuntu 17.10
- running `rpyc_classic.py`

**Comment by szabgab** [comment]
thanks
