### ISSUE TITLE
Redirecting loggers.

### ISSUE THREAD

**Issue by SergeyYanos** [tomerfiliba/rpyc#275]
Hi,
What is the correct way to redirect the remote loggers to local side?

In the example below only stdout.write is being redirected, remote_logger.info('hello world!') is still being printed on the remote side.

##### Environment

- rpyc version: 3.4.4
- python version: 2.7
- operating system: Fedora 27

##### Minimal example

Server:
> python rpyc_classic.py --host 0.0.0.0

Client:

    from rpyc.utils.classic import redirected_stdio, connect

    logger = logging.getLogger('main')
    logger.debug('Starting test')

    conn = connect(host, port)

    remote_logger = conn.modules.logging.getLogger()
    with redirected_stdio(conn):
        conn.modules.sys.stdout.write('hello world!')
        conn.modules.sys.stdout.flush()
        remote_logger.info('hello world!')

    logger.debug('Test finished!')

Thanks!

**Comment by coldfix** [comment]
Looking at the implementation of the standard logging module, it seems that `logging.StreamHandler` saves `sys.stderr` when it is instanciated. Therefore, in order to alter the behaviour of logging, you would need to redirect stderr before setting up logging.

Alternatively, you can try replacing the logger as in #207:

```python
rlogger = r.modules.logging.getLogger()
rlogger.parent=logging.getLogger()
```

Does this help?

**Comment by SergeyYanos** [comment]
Hi @coldfix, thanks for the quick response. 
I tried both options and the first one didn't work.
The second one did, I've changed the client side to:

    ```
    from rpyc.utils.classic import redirected_stdio, connect

    logger = logging.getLogger('main')
    logger.debug('Starting test')

    conn = connect(host, port)
    remote_logger = conn.modules.logging.getLogger()
    remote_logger.parent = logger
    remote_logger.info('hello world!')

    logger.debug('Test finished!')
    ```
and the "hello world" did show up on the local side as I wanted but I started getting errors on the server side:

> [root@reg-l-vrt-5175-007 rpyc]# python bin/rpyc_classic.py --host 0.0.0.0
08:07:54        server.py:248             [SLAVE/18812] INFO : server started on [0.0.0.0]:18812
08:07:57        server.py:154             [SLAVE/18812] INFO : accepted ('10.135.174.7', 57568) with fd 4
08:07:57        server.py:197             [SLAVE/18812] INFO : welcome ('10.135.174.7', 57568)
08:07:57        protocol.py:652             [root ] INFO : hello world!
08:07:57        server.py:204             [SLAVE/18812] INFO : goodbye ('10.135.174.7', 57568)
08:07:57        server.py:182             [SLAVE/18812] ERROR : client connection terminated abruptly
Traceback (most recent call last):
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/utils/server.py", line 180, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/utils/server.py", line 204, in _serve_client
    self.logger.info("goodbye %s", addrinfo)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1333, in callHandlers
    for hdlr in c.handlers:
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/netref.py", line 159, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/netref.py", line 77, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/protocol.py", line 518, in sync_request
    self._send_request(seq, handler, args)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/protocol.py", line 268, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/protocol.py", line 263, in _send
    self._channel.send(data)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/channel.py", line 69, in send
    self.stream.write(buf)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/stream.py", line 233, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/stream.py", line 82, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/utils/server.py", line 182, in _authenticate_and_serve_client
    self.logger.exception("client connection terminated abruptly")
  File "/usr/lib64/python2.7/logging/__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1333, in callHandlers
    for hdlr in c.handlers:
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/netref.py", line 159, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/netref.py", line 77, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/protocol.py", line 518, in sync_request
    self._send_request(seq, handler, args)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/protocol.py", line 268, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/protocol.py", line 263, in _send
    self._channel.send(data)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/channel.py", line 69, in send
    self.stream.write(buf)
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/stream.py", line 233, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/.autodirect/swgwork/sergeyy/git/rpyc/rpyc/core/stream.py", line 82, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed

**Comment by coldfix** [comment]
Hi, the error you see is due to the fact that the server tries to log after the client has been disconnected. This will of course result in `EOFError`. As you realized, you have to restore `remote_logger.parent` when the client disconnects. This is of course not trivial (in the case of unforseen connection errors etc).

It would probably be cleanest to subclass `logging.StreamHandler` in a way that it can deal properly with `EOFError` and register your handler only *additionally* to local logging handlers (using e.g. `Logger.addHandler`).

You should also consider registering your handler for only a certain domain (logger name) - so only a selected subset of logging events are forwarded via rpyc.

If you find a clean solution, I'm open to merge a PR for this.

Best, Thomas
