### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by bor8** [tomerfiliba/rpyc#277]
```
# 3.4.4

python3 /usr/local/bin/rpyc_classic.py --ipv6

INFO:SLAVE/18812:server started on [::]:18812
```

versus

```
# 4.0.0

python3 /usr/local/bin/rpyc_classic.py --ipv6

Traceback (most recent call last):
  File "/usr/local/bin/rpyc_classic.py", line 125, in <module>
    ClassicServer.run()
  File "/usr/local/lib/python3.5/dist-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/bin/rpyc_classic.py", line 85, in main
    self._serve_mode(ThreadedServer)
  File "/usr/local/bin/rpyc_classic.py", line 96, in _serve_mode
    registrar = self.registrar, auto_register = self.auto_register)
  File "/usr/local/lib/python3.5/dist-packages/rpyc/utils/server.py", line 89, in __init__
    self.listener.bind((hostname, port))
socket.gaierror: [Errno -9] Address family for hostname not supported
```

**Comment by coldfix** [comment]
Thanks, fixed. Can you work on the master branch and report further issues before I make the next release?

**Comment by bor8** [comment]
Yes:

```
# 4.0.1

python3 /usr/local/bin/rpyc_classic.py --ipv6

INFO:SLAVE/18812:server started on [::1]:18812
```

I'm afraid that doesn't quite fit: [::] (listen on every interface) versus [::1] (listen on localhost).

**Comment by coldfix** [comment]
That's on purpose and mentioned in the 4.0 changelog. IMO, it's a bad idea to expose classic service (i.e. arbitrary code execution) on all network interfaces by default. You can still easily do that manually `rpyc_classic.py --ipv6 --host '::'

**Comment by bor8** [comment]
Well, if you fix that too, you're the best. ;)

**Comment by bor8** [comment]
Cool, thanks, you are the best. ^^
