### ISSUE TITLE
Cannot use ParamikoMachine instead of SshMachine

### ISSUE THREAD

**Issue by Denton-L** [tomerfiliba/rpyc#288]
Currently, I am attempting to run rpyc over SSH. It is currently working with `SshMachine`, however because we can't depend on having a Bash environment available, we are attempting to switch over to ParamikoMachine.

According to the [documentation](https://rpyc.readthedocs.io/en/latest/api/utils_factory.html#rpyc.utils.factory.ssh_connect), the method should accept a `plumbum.remote.RemoteMachine` instance. However, it seems like the `tunnel` method is only defined in `SshMachine`.

The following is the stacktrace of the 

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    connection = rpyc.utils.factory.ssh_connect(remote_machine, port)
  File "C:\cygwin64\home\dl1039488\bose-workspace\polycomm-env\lib\site-packages\rpyc\utils\factory.py", line 184, in ssh_connect
    tun = remote_machine.tunnel(loc_port, remote_port)
AttributeError: 'ParamikoMachine' object has no attribute 'tunnel'```


##### Environment

- rpyc 4.0.1
- python 3.6.5
- paramiko 2.4.1
- plumbum 1.6.6
- Windows 10 with Cygwin


##### Minimal example

Client:

Note that the line with `SshMachine` works but the line with `ParamikoMachine` crashes.

```python
import rpyc.utils.factory
from paramiko import AutoAddPolicy
from plumbum.machines.paramiko_machine import ParamikoMachine
from plumbum import SshMachine

hostname = "10.5.22.180"
user = "pi"
port = 22
keyfile = r"C:\cygwin64\home\dl1039488\.ssh\id_rsa"

#remote_machine = SshMachine(hostname, user, port, keyfile)
remote_machine = ParamikoMachine(hostname, user, port, keyfile, missing_host_policy=AutoAddPolicy())
connection = rpyc.utils.factory.ssh_connect(remote_machine, port)
```

**Comment by coldfix** [comment]
Hi,

unfortunately I'm not very acquainted with paramaiko/plumbum and currently don't have time to get into that. If you look at the source of the [`ssh_connect`](https://rpyc.readthedocs.io/en/latest/_modules/rpyc/utils/factory.html#ssh_connect) function, you'll see that it is not very complicated. Can you try writing your own replacement that works with paramaiko and submit the code here, so we can integrate it into rpyc?

Best, Thomas

**Comment by tawy** [comment]
Hi,

I have investigated the ParamikoMachine pipeline for my own needs and I came up with the following solution:

```python
import rpyc
from plumbum.machines.paramiko_machine import ParamikoMachine
from paramiko import AutoAddPolicy

remote_port = 12345
kwargs = {
 "host" = "myhostname",
 "user" = "myusername",
 "port" = 22,
 "missing_host_policy" = AutoAddPolicy(),
 # Any other parameter
}

remote_machine = ParamikoMachine(**kwargs)

sock = remote_machine.connect_sock(remote_port)
stream = rpyc.core.stream.SocketStream(sock)
connection = rpyc.connect_stream(stream)
```

(given that a ThreadedServer has been launched on remote machine on port `remote_port` )

Hope this helps,
Best, Tawy
