### ISSUE TITLE
Traceback with "rpyc.classic.connect()" on EV3DEV

### ISSUE THREAD

**Issue by Maahess** [tomerfiliba/rpyc#296]
I am using python provided rpyc module for my remote connectivity purposes but my command "import rpyc; conn = rpyc.classic.connect()" yield the following traceback:
>>> import rpyc
>>> conn = rpyc.classic.connect('192.168.137.194')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\utils\classic.py", line 70, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\utils\factory.py", line 94, in connect
    return connect_stream(s, service, config)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\utils\factory.py", line 55, in connect_stream
    return connect_channel(Channel(stream), service=service, config=config)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\utils\factory.py", line 44, in connect_channel
    return service._connect(channel, config)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\core\service.py", line 100, in _connect
    self.on_connect(conn)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\core\service.py", line 195, in on_connect
    self._install(conn, conn.root)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\core\service.py", line 199, in _install
    modules = ModuleNamespace(slave.getmodule)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\core\netref.py", line 155, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\core\netref.py", line 75, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\core\protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\Users\Cuza\AppData\Roaming\Python\Python27\site-packages\rpyc\core\async_.py", line 97, in value
    raise self._obj
rpyc.core.vinegar/builtins.KeyError: <rpyc.core.service.SlaveService object at 0xb59a5050>

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/protocol.py", line 347, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/protocol.py", line 630, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/protocol.py", line 588, in _access_attr
    obj = self._local_objects[oid]
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/lib/colls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: <rpyc.core.service.SlaveService object at 0xb59a5050>

And on Putty console i get this:
robot@ev3dev:~$ ./rpyc_server.sh
INFO:SLAVE/18812:server started on [0.0.0.0]:18812
INFO:SLAVE/18812:accepted ('192.168.137.1', 64846) with fd 4
INFO:SLAVE/18812:welcome ('192.168.137.1', 64846)
DEBUG:SLAVE/18812:Exception caught
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 347, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 630, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", ge                                                                                        tattr)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 588, in _access_attr
    obj = self._local_objects[oid]
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/lib/col                                                                                        ls.py", line 86, in __getitem__
    return self._dict[key][0]
KeyError: <rpyc.core.service.SlaveService object at 0xb59a5050>
INFO:SLAVE/18812:goodbye ('192.168.137.1', 64846)
ERROR:SLAVE/18812:client connection terminated abruptly
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/utils/s                                                                                        erver.py", line 179, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/utils/s                                                                                        erver.py", line 202, in _serve_client
    conn._init_service()
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 164, in _init_service
    self._local_root.on_connect()
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/se                                                                                        rvice.py", line 142, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/ne                                                                                        tref.py", line 151, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/ne                                                                                        tref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 519, in sync_request
    self.sync_recv_and_dispatch(timeout, True)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 417, in sync_recv_and_dispatch
    self._dispatch(data)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 405, in _dispatch
    self._dispatch_exception(seq, args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 374, in _dispatch_exception
    instantiate_oldstyle_exceptions = self._config["instantiate_oldstyle_excepti                                                                                        ons"])
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/vi                                                                                        negar.py", line 158, in load
    setattr(exc, name, attrval)
TypeError: attribute name must be string, not 'bytes'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/utils/s                                                                                        erver.py", line 179, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/utils/s                                                                                        erver.py", line 202, in _serve_client
    conn._init_service()
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 164, in _init_service
    self._local_root.on_connect()
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/se                                                                                        rvice.py", line 142, in on_connect
    self._conn.modules = ModuleNamespace(self._conn.root.getmodule)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/ne                                                                                        tref.py", line 151, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/ne                                                                                        tref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 519, in sync_request
    self.sync_recv_and_dispatch(timeout, True)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 417, in sync_recv_and_dispatch
    self._dispatch(data)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 405, in _dispatch
    self._dispatch_exception(seq, args)
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/pr                                                                                        otocol.py", line 374, in _dispatch_exception
    instantiate_oldstyle_exceptions = self._config["instantiate_oldstyle_excepti                                                                                        ons"])
  File "/usr/local/lib/python3.5/dist-packages/rpyc-3.4.4-py3.5.egg/rpyc/core/vi                                                                                        negar.py", line 158, in load
    setattr(exc, name, attrval)
TypeError: attribute name must be string, not 'bytes'

Environment:
rpyc version = 3.4.4(on both pc and ev3)
Can anyone please help me rectify this issue?

**Comment by coldfix** [comment]
Hi, thanks for reporting. Unfortunately your post is hard to read to due to missing code-markers and may be missing useful information. Please take a look at the issue template that comes up when you click "New issue" and re-submit accordingly.

**Comment by coldfix** [comment]
Hi, as I mentioned it's nearly impossible to read your post. However, it looks like you're using python27 on one end and python34 on the other end - which is not supported. Make sure to use the same python version on both sides. If you continue to have problems, please open a new issue and follow the submission guidelines.
