### ISSUE TITLE
Some tests fail on a single core machine

### ISSUE THREAD

**Issue by arcresu** [tomerfiliba/rpyc#299]
When running the tests on a single core machine the three tests in `test_teleportation` fail, and some `select()`-related errors are raised. I'm not sure if this environment is one you want to support for running tests, but if not then would you consider skipping the affected tests when a single core environment is detected?

This was [reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907716) during Debian packaging when I updated the package there to from 3.4.4 to 4.0.2.

I can reproduce the failure using `taskset` on Linux with python3.6:

```bash
nosetests3 -vv -I test_deploy -I test_gevent_server -I test_ssh
# => all OK

taskset -c 0 nosetests3 -vv -I test_deploy -I test_gevent_server -I test_ssh
# => fails
```
Here are the specific failures:

```
======================================================================
ERROR: test (test_teleportation.TeleportationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/carl/code/rpyc/tests/test_teleportation.py", line 45, in setUp
    self.conn = rpyc.classic.connect(host, int(port))
  File "/home/carl/code/rpyc/rpyc/utils/classic.py", line 70, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "/home/carl/code/rpyc/rpyc/utils/factory.py", line 94, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 154, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 112, in _connect
    s.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
-------------------- >> begin captured logging << --------------------
SLAVE/18812: INFO: server has terminated
SLAVE/18812: INFO: goodbye ('127.0.0.1', 43594)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_def (test_teleportation.TeleportationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/carl/code/rpyc/tests/test_teleportation.py", line 45, in setUp
    self.conn = rpyc.classic.connect(host, int(port))
  File "/home/carl/code/rpyc/rpyc/utils/classic.py", line 70, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "/home/carl/code/rpyc/rpyc/utils/factory.py", line 94, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 154, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 112, in _connect
    s.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused

======================================================================
ERROR: test_globals (test_teleportation.TeleportationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/carl/code/rpyc/tests/test_teleportation.py", line 45, in setUp
    self.conn = rpyc.classic.connect(host, int(port))
  File "/home/carl/code/rpyc/rpyc/utils/classic.py", line 70, in connect
    return factory.connect(host, port, SlaveService, ipv6 = ipv6, keepalive = keepalive)
  File "/home/carl/code/rpyc/rpyc/utils/factory.py", line 94, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 154, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 112, in _connect
    s.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused

----------------------------------------------------------------------
```

These errors also occur earlier but don't result in any test failures:
```
test_properties (test_attributes.TestAttributes) ... Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 40, in poll
    p.register(self.fileno(), "r")
  File "/home/carl/code/rpyc/rpyc/lib/compat.py", line 99, in register
    self._poll.register(fd, flags)
ValueError: file descriptor cannot be a negative integer (-1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 181, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 203, in _serve_client
    self._handle_connection(conn)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 209, in _handle_connection
    conn.serve_all()
  File "/home/carl/code/rpyc/rpyc/core/protocol.py", line 413, in serve_all
    self.serve(None)
  File "/home/carl/code/rpyc/rpyc/core/protocol.py", line 387, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/home/carl/code/rpyc/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 58, in poll
    raise select_error(str(ex))
OSError: file descriptor cannot be a negative integer (-1)

test_connection (test_threaded_server.Test_ThreadedServerOverUnixSocket) ... Exception in thread Thread-56:
Traceback (most recent call last):
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 40, in poll
    p.register(self.fileno(), "r")
  File "/home/carl/code/rpyc/rpyc/lib/compat.py", line 99, in register
    self._poll.register(fd, flags)
ValueError: file descriptor cannot be a negative integer (-1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 181, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 203, in _serve_client
    self._handle_connection(conn)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 209, in _handle_connection
    conn.serve_all()
  File "/home/carl/code/rpyc/rpyc/core/protocol.py", line 413, in serve_all
    self.serve(None)
  File "/home/carl/code/rpyc/rpyc/core/protocol.py", line 387, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/home/carl/code/rpyc/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 58, in poll
    raise select_error(str(ex))
OSError: file descriptor cannot be a negative integer (-1)

ok
test_invoker (test_threads.Test_Multithreaded) ... Exception in thread Thread-58:
Traceback (most recent call last):
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 40, in poll
    p.register(self.fileno(), "r")
  File "/home/carl/code/rpyc/rpyc/lib/compat.py", line 99, in register
    self._poll.register(fd, flags)
ValueError: file descriptor cannot be a negative integer (-1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 181, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 203, in _serve_client
    self._handle_connection(conn)
  File "/home/carl/code/rpyc/rpyc/utils/server.py", line 209, in _handle_connection
    conn.serve_all()
  File "/home/carl/code/rpyc/rpyc/core/protocol.py", line 413, in serve_all
    self.serve(None)
  File "/home/carl/code/rpyc/rpyc/core/protocol.py", line 387, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/home/carl/code/rpyc/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/home/carl/code/rpyc/rpyc/core/stream.py", line 58, in poll
    raise select_error(str(ex))
OSError: file descriptor cannot be a negative integer (-1)
```

##### Environment

- rpyc version: 4.0.2 git HEAD 59efbf2938481a4b597c11c73bdc6a5f60aa90e5
- python version: Python 3.6.6
- operating system: Debian sid `Linux 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux`

**Comment by coldfix** [comment]
Thanks for the info. I can't think of any reason why it shouldn't be supported off the top of my head, I will take a closer look as soon as possible. However, I can't guarantee to do it this week.

**Comment by arcresu** [comment]
Thanks for looking into the problem :+1:
