### ISSUE TITLE
Problem with __hash__ for protocol_config={'allow_all_attrs': True}

### ISSUE THREAD

**Issue by ps-lukin-siv** [tomerfiliba/rpyc#324]
I'm creating a server in one Jupyter Notebook and want to connect to it from a different Notebook.

When `protocol_config={'allow_all_attrs': False}`, everything works fine. But when `protocol_config={'allow_all_attrs': True}`, it produces TypeError.

##### Environment
- rpyc version: 4.0.2
- python version: 3.7.0
- operating system: Windows 10
- ipykernel: 4.10.0
- ipython: 6.5.0

##### Minimal example

Server:
```python
import rpyc
from rpyc.utils.server import ThreadedServer

class MyService(rpyc.Service):
    def on_connect(self, conn):
        pass

    def on_disconnect(self, conn):
        pass

    def exposed_get_answer(self):
        return 50

t = ThreadedServer(
    MyService,
    port=18861,
    protocol_config={'allow_all_attrs': True}
)
t.start()
```
Client:
```python
import rpyc
c = rpyc.connect("localhost", 18861)

c.root
```
`c.root` call produces the following error message (in fact, many repetitions of this block):
```stack trace / error log
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
C:\Anaconda\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    907             # lookup registered printer
    908             try:
--> 909                 printer = self.lookup(obj)
    910             except KeyError:
    911                 pass

C:\Anaconda\lib\site-packages\IPython\core\formatters.py in lookup(self, obj)
    393             return self.singleton_printers[obj_id]
    394         # then lookup by type
--> 395         return self.lookup_by_type(_get_type(obj))
    396 
    397     def lookup_by_type(self, typ):

C:\Anaconda\lib\site-packages\IPython\core\formatters.py in lookup_by_type(self, typ)
    423         else:
    424             for cls in pretty._get_mro(typ):
--> 425                 if cls in self.type_printers or self._in_deferred_types(cls):
    426                     return self.type_printers[cls]
    427 

C:\Anaconda\lib\site-packages\rpyc\core\netref.py in method(_self, *args, **kwargs)
    218         def method(_self, *args, **kwargs):
    219             kwargs = tuple(kwargs.items())
--> 220             return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
    221         method.__name__ = name
    222         method.__doc__ = doc

C:\Anaconda\lib\site-packages\rpyc\core\netref.py in syncreq(proxy, handler, *args)
     73     """
     74     conn = object.__getattribute__(proxy, "____conn__")
---> 75     return conn.sync_request(handler, proxy, *args)
     76 
     77 def asyncreq(proxy, handler, *args):

C:\Anaconda\lib\site-packages\rpyc\core\protocol.py in sync_request(self, handler, *args)
    469         """
    470         timeout = self._config["sync_request_timeout"]
--> 471         return self.async_request(handler, *args, timeout=timeout).value
    472 
    473     def _async_request(self, handler, args = (), callback = (lambda a, b: None)):

C:\Anaconda\lib\site-packages\rpyc\core\async_.py in value(self)
     95         self.wait()
     96         if self._is_exc:
---> 97             raise self._obj
     98         else:
     99             return self._obj

TypeError: descriptor '__hash__' of 'object' object needs an argument

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\rpyc\core\protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Anaconda\lib\site-packages\rpyc\core\protocol.py", line 603, in _handle_callattr
    return self._handle_call(obj, args, kwargs)
  File "C:\Anaconda\lib\site-packages\rpyc\core\protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
TypeError: descriptor '__hash__' of 'object' object needs an argument
```

**Comment by comrumino** [comment]
The fix for this issue has been [merge](https://github.com/tomerfiliba/rpyc/commit/39f386e50b8742e4b4f82ebc709ea978af20ff70)
