### ISSUE TITLE
RPyC client in python 2 cannot make requests to RPyC server running python 3.

### ISSUE THREAD

**Issue by DonaldKevin** [tomerfiliba/rpyc#327]
I was experimenting, and I discovered that a client and a server have to be running the same version of python to talk to each other.

Don't know if it is a huge problem, or even something you want to support.

rpyc-4.0.2
ubuntu 18.04

first case python3 server, python2 client
```
Traceback (most recent call last):
  File "./matlabClient.py", line 17, in <module>
    r = c.root.performMatlab("gcd", *l)
  File "/home/lafayette/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 199, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/home/lafayette/.local/lib/python2.7/site-packages/rpyc/core/netref.py", line 75, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/home/lafayette/.local/lib/python2.7/site-packages/rpyc/core/protocol.py", line 471, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/home/lafayette/.local/lib/python2.7/site-packages/rpyc/core/async_.py", line 97, in value
    raise self._obj
rpyc.core.vinegar/builtins.TypeError: must be str, not bytes

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/home/lafayette/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 329, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/lafayette/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 590, in _handle_call
    return obj(*args, **dict(kwargs))
  File "matlabService.py", line 162, in exposed_performMatlab
    return performMatlab(theMatlabFunc, *args, **kwargs)
  File "matlabService.py", line 121, in performMatlab
    " " + repr(args) + " " + repr(kwargs))
TypeError: must be str, not bytes

```
second case python2 server, python 3 client
```
Traceback (most recent call last):
  File "matlabClient.py", line 17, in <module>
    r = c.root.performMatlab("gcd", *l)
TypeError: 'b'instancemethod'' object is not callable
```

**Comment by comrumino** [comment]
Since python 2.7 will not be maintained beyond 2020, I'd rather not endorse the use of soon to be no longer maintained versions. Adding this support would violate the projects *transparent* aim as well. Rather than marking this `won't fix`, I'll agree that the error logging should be better for when people attempt to use unsupported client-server combinations.

**Comment by comrumino** [comment]
Closing this as it now falls under #332
