### ISSUE TITLE
Builtin json.dumps fails on transmitted dict

### ISSUE THREAD

**Issue by nasefbasdf** [tomerfiliba/rpyc#335]
Hi!

There is a procedure which I need to call through RPyC in which a passed argument needs to be JSON serialized. This does not work unfortunately. I think the JSON encoder does not recognize the transmitted object's type.

I expect the dict to be serialized, but `TypeError` is raised instead.

## Reproducing the error
I use a virtualenv in the example located at `C:\L\testing27` while the real interpreter is at `C:\Programs\Python27`.
### Server
To reproduce start a classic server:
```
C:\L\testing27>Scripts\activate.bat
(testing27) C:\L\testing27>python Scripts/rpyc_classic.py
INFO:SLAVE/18812:server started on [127.0.0.1]:18812
```
### Client
Open a client connection and try encoding a dict to JSON:
```
C:\L\testing27>Scripts\activate.bat
(testing27) C:\L\testing27>python
>>> import rpyc
>>> c = rpyc.classic.connect("localhost")
>>> c.modules['json'].dumps({})
```
### Traces
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\L\testing27\lib\site-packages\rpyc\core\netref.py", line 242, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "C:\L\testing27\lib\site-packages\rpyc\core\netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\L\testing27\lib\site-packages\rpyc\core\protocol.py", line 455, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\L\testing27\lib\site-packages\rpyc\core\async_.py", line 102, in value
    raise self._obj
TypeError: {} is not JSON serializable

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\L\testing27\lib\site-packages\rpyc\core\protocol.py", line 322, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\L\testing27\lib\site-packages\rpyc\core\protocol.py", line 577, in _handle_call
    return obj(*args, **dict(kwargs))
  File "C:\Programs\Python27\Lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "C:\Programs\Python27\Lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Programs\Python27\Lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Programs\Python27\Lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {} is not JSON serializable
```

## Environment

- rypc 4.1.0
- python 2.7.15
- Windows 10

**Comment by comrumino** [comment]
`>>> c.modules['json'].dumps({})`
should be
`>>> c.modules['json'].dumps(rpyc.classic.deliver(c, mydic))`
for non-trivial types. In most cases, it makes sense to dump the object before passing it as a parameter and load before returning the result.
