### ISSUE TITLE
Regression with IronPython on RPyC v4.1.0

### ISSUE THREAD

**Issue by pilcru** [tomerfiliba/rpyc#337]
a63c27e53c709d02e6df995c2bd1bdb34fa6eaaa re-introduces incompatibilities of RPyC with IronPython that were initially referenced in #10. The issue is that in IronPython, `str == unicode`, and the CPython side unboxes objects of that type to `unicode`. This in turns leads to various problems in functions like `type()` that expect `str` objects.

A simple fix is to replace [this line](https://github.com/tomerfiliba/rpyc/blob/2f2a43e3538e4f6f21c0106a2f51a92ffcd623fb/rpyc/core/protocol.py#L296) with:

```
id_pack = (str(value[0]), value[1], value[2])
```

to bring back the behavior that was [there before](https://github.com/tomerfiliba/rpyc/blob/9cbe40b489b9c46d7263c08fcd34fbfaf161e764/rpyc/core/netref.py#L289-L290). I feel like it's safer to do the cast during unboxing rather than in `class_factory`, to prevent the id_pack to ever exist as two different types, but that's just a suggestion.

This bug shows up when connecting IronPython 2.7.9 to CPython 2.7.16 on Windows 10 64bits, rpyc v4.1.0.

Server = IronPython:

```python
import rpyc
from rpyc.utils.server import OneShotServer
rpyc.lib.setup_logger()

class ListService(rpyc.Service):
    def exposed_concat(self, lst):
        return [x for x in lst] + ['world']

server = OneShotServer(ListService, port=12345)
server.start()
```

Client = CPython:

```python
import rpyc
c = rpyc.connect("localhost", 12345)
print(c.root.concat(['hello']))
```

Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 485, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 455, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\async_.py", line 100, in value
    self.wait()
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\async_.py", line 47, in wait
    self._conn.serve(self._ttl)
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 384, in serve
    self._dispatch(data)
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 352, in _dispatch
    obj = self._unbox(args)
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 300, in _unbox
    proxy = self._netref_factory(id_pack)
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\protocol.py", line 314, in _netref_factory
    cls = netref.class_factory(id_pack, cls_methods)
  File "C:\Users\pierre\AppData\Local\Continuum\anaconda3\envs\rhinoremote\lib\site-packages\rpyc\core\netref.py", line 302, in class_factory
    return type(name_pack, (BaseNetref,), ns)
TypeError: type() argument 1 must be string, not unicode
```

**Comment by comrumino** [comment]
Thanks! I'll try to test this moving forward since I now have it configured.
