### ISSUE TITLE
Timeout even if doing something

### ISSUE THREAD

**Issue by XonqNopp** [tomerfiliba/rpyc#356]
I have a use case where we need to do a long operation on the remote server. It runs fine, and we even have the remote log showing on the local client what is happening. But suddenly it aborts because of the timeout, even though everything was working AND there was some traffic on the RPyC channel... I understand that if there was no communication AT ALL it should abort because of a predefined timeout, but here I had continuously log coming from the server...

## Environment

- rpyc version: 4.1.0
- python version: 3.5
- operating system:
  - client: Debian 9 or Windows 10
  - server: Debian-based buildroot (for MWE: Debian 9)

### Server

```python
from rpyc.utils.server import ThreadedServer
import rpyc
import time
import logging


logging.basicConfig(level=logging.DEBUG)


class S(rpyc.SlaveService):
    def exposed_f(self, timeout):
        log = logging.getLogger('ping')
        r = 2 * timeout
        for i in range(r):
            time.sleep(1)
            log.warning('pong @ {}/{}'.format(i + 1, r))


t = ThreadedServer(S, port=5001)
t.start()
```

#### Stack trace

```
INFO:S/5001:server started on [0.0.0.0]:5001
INFO:S/5001:accepted ('127.0.0.1', 42382) with fd 4
INFO:S/5001:welcome ('127.0.0.1', 42382)
WARNING:ping:pong @ 1/10
WARNING:ping:pong @ 2/10
WARNING:ping:pong @ 3/10
WARNING:ping:pong @ 4/10
WARNING:ping:pong @ 5/10

DEBUG:S/5001:Exception caught

Traceback (most recent call last):
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 322, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 577, in _handle_call
    return obj(*args, **dict(kwargs))
  File "rpyc_server.py", line 18, in exposed_f
    log.warning('pong @ {}/{}'.format(i + 1, r))
  File "/usr/lib/python3.5/logging/__init__.py", line 1292, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1416, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1426, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1485, in callHandlers
    for hdlr in c.handlers:
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 161, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 455, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/async_.py", line 100, in value
    self.wait()
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/async_.py", line 47, in wait
    self._conn.serve(self._ttl)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 384, in serve
    self._dispatch(data)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 350, in _dispatch
    self._dispatch_request(seq, args)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 336, in _dispatch_request
    self._send(consts.MSG_REPLY, seq, self._box(res))
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 258, in _send
    self._channel.send(data)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/channel.py", line 75, in send
    self.stream.write(buf)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 267, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 94, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed


INFO:S/5001:goodbye ('127.0.0.1', 42382)
ERROR:S/5001:client connection terminated abruptly


Traceback (most recent call last):
  File "_venv/default/lib/python3.5/site-packages/rpyc/utils/server.py", line 180, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "_venv/default/lib/python3.5/site-packages/rpyc/utils/server.py", line 204, in _serve_client
    self.logger.info("goodbye %s", addrinfo)
  File "/usr/lib/python3.5/logging/__init__.py", line 1280, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1416, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1426, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1485, in callHandlers
    for hdlr in c.handlers:
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 161, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 455, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 476, in async_request
    self._async_request(handler, args, res)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 461, in _async_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 258, in _send
    self._channel.send(data)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/channel.py", line 75, in send
    self.stream.write(buf)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 267, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 94, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed

Exception in thread Thread-1:

Traceback (most recent call last):
  File "_venv/default/lib/python3.5/site-packages/rpyc/utils/server.py", line 180, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "_venv/default/lib/python3.5/site-packages/rpyc/utils/server.py", line 204, in _serve_client
    self.logger.info("goodbye %s", addrinfo)
  File "/usr/lib/python3.5/logging/__init__.py", line 1280, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1416, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1426, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1485, in callHandlers
    for hdlr in c.handlers:
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 161, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 455, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 476, in async_request
    self._async_request(handler, args, res)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 461, in _async_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 258, in _send
    self._channel.send(data)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/channel.py", line 75, in send
    self.stream.write(buf)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 267, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 94, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "_venv/default/lib/python3.5/site-packages/rpyc/utils/server.py", line 182, in _authenticate_and_serve_client
    self.logger.exception("client connection terminated abruptly")
  File "/usr/lib/python3.5/logging/__init__.py", line 1315, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1309, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1416, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1426, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1485, in callHandlers
    for hdlr in c.handlers:
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 161, in __getattribute__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 455, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 476, in async_request
    self._async_request(handler, args, res)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 461, in _async_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 258, in _send
    self._channel.send(data)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/channel.py", line 75, in send
    self.stream.write(buf)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 267, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/stream.py", line 94, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
```

### Client

```python
import sys
import logging
from rpyc.utils.classic import connect


h = logging.StreamHandler(sys.stdout)
logging.basicConfig(level=logging.DEBUG, handlers=[h])

timeout = 5


localLog = logging.getLogger('local')


c = connect('127.0.0.1', port=5001)
c._config['sync_request_timeout'] = timeout

remoteLog = c.modules.logging.getLogger()
remoteLog.parent = localLog

c.root.exposed_f(timeout)

remoteLog.parent = None
```

#### Stack trace

```
WARNING:ping:pong @ 1/10
WARNING:ping:pong @ 2/10
WARNING:ping:pong @ 3/10
WARNING:ping:pong @ 4/10

Traceback (most recent call last):
  File "rpyc_client.py", line 22, in <module>
    c.root.exposed_f(timeout)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 242, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/netref.py", line 76, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/protocol.py", line 455, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/async_.py", line 100, in value
    self.wait()
  File "_venv/default/lib/python3.5/site-packages/rpyc/core/async_.py", line 49, in wait
    raise AsyncResultTimeout("result expired")
TimeoutError: result expired
```

**Comment by comrumino** [comment]
This behavior is expected.

**Synchronous** requests should complete within a predictable amount of time. When we don't know how long the request will take, **asynchronous** behavior is desired. If a synchronous request times out and the time to complete the request is predictable, adjust the timeout accordingly. Otherwise, use asynchronous requests.
