### ISSUE TITLE
[Help] How to have a host make and receive RpyC connections at the same time?

### ISSUE THREAD

**Issue by kckusal** [tomerfiliba/rpyc#359]
I only recently started using RPyC, so I am not sure what's causing this, so forgive me if this question is too naive.  Here's my situation.

I have a NameServer, a client and an external server. Every 60 seconds, Nameserver tries to connect to the external server using RPyC to see if it responding or not (say check_aliveness() function). Now, when I try to connect to Nameserver from my client using RPyC, it refuses to connect with following stack trace:

```
Traceback (most recent call last):
  File "client.py", line 449, in <module>
    main()
  File "client.py", line 436, in main
    CONN = rpyc.connect(NAME_SERVER["IP"], NAME_SERVER["PORT"])
  File "/usr/local/lib/python3.7/site-packages/rpyc/utils/factory.py", line 98, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "/usr/local/lib/python3.7/site-packages/rpyc/core/stream.py", line 172, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/rpyc/core/stream.py", line 124, in _connect
    s = socket_backoff_connect(family, socktype, proto, sockaddr, timeout, attempts)
  File "/usr/local/lib/python3.7/site-packages/rpyc/lib/__i    sock.connect(addr)
ConnectionRefusedError: [Errno 111] Connection refused     

```

I am expecting the client to be able to connect to the NameServer normally using RPyC, even if the NameServer is connecting to another remote server using RPyC at the same time.

Now, if I were to remove that check_aliveness() function I referenced above, i.e. not have NameServer make any connections to other servers, I see that the client is able to connect to the Nameserver normally.

Now, it should be possible for the NameServer to act as a client (connecting to other servers), and act as server (accept connections from others) at the same time using RPyC, right? How do I achieve this?

Python version: 3.7.3
RPyC version: 4.1.2

Environment: Debian OS

I tried using different ports for each of the connections I created, but the result is same as above. Client is able to use RPyC to connect to NameServer only if the NameServer is not connecting (or not connected) to any other Server at the same time.

I also thought it might work if the NameServer is to release any external connection made using RPyC immediately upon completion of desired task, but how do I manually release an RPyC connection?? I tried setting some values, but didn't seem to work.

Perhaps I am not approaching this the right way, but like I said, I only started using RPyC a couple days ago. Any help is appreciated.)

**Comment by kckusal** [comment]
Okay, it seems the problem was something else, not RPyC, in my program-with threading to be specific. It's resolved now.
