### ISSUE TITLE
Trying to use decoupling results in a timeout

### ISSUE THREAD

**Issue by FestinaLente666** [tomerfiliba/rpyc#380]
Sorry if this is a silly question, I'm not a programmer. I tried asking anywhere else I know first.

I have two types of services, I connect to one service while using the other service for replies, as described in the RPyC manual. But for some reason I get a time out when trying to use the reply service.

I tried to call the service in several different locations in the code, thinking maybe the introspection is making stuff go haywire, but no dice.

I also tried to separate the client and server to two different services, but I got the exact same result.

I tried to clean up the code as much as I could, but I left my original imports and custom configuration in case this might be related, though cleaning those up too doesn't resolve the issue.

I have no idea why this is timing out. I reproduced the issue in the simplest form I could.

code:
```

    import rpyc, sys, threading, time, socket, random
    from rpyc.utils.server import ThreadedServer
    from rpyc.utils.helpers import classpartial
    from threading import Lock
    import os, inspect
    currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
    parentdir = os.path.dirname(currentdir)
    sys.path.insert(0,parentdir)
    from dag import DAG
    import logging
    import copy
     
    RPYC_CFG = {"allow_all_attrs": True, "allow_pickle": True}
     
    logging.basicConfig(
        format='%(asctime)s %(levelname)-8s %(message)s',
        level=logging.DEBUG, filename="log.txt",
        datefmt='%Y-%m-%d %H:%M:%S')
     
    class netAddr:
        def __init__(self, host, mport):
            self.host = host
            self.mport = mport
     
    class NodeManagerService(rpyc.Service):
        def __init__(self, node):
            self.node = node
     
        def on_connect(self, conn):
            self.node.manager = conn
            #don't work either:
            #conn.root.foo("bar0")
            #self.node.manager.root.foo("bar1")
     
    class Node:
        def __init__(self, addr):
            self.manager_thread = ThreadedServer(classpartial(NodeManagerService, self), hostname=addr.host, port=addr.mport, protocol_config=RPYC_CFG)
            threading.Thread(target=self.manager_thread.start).start()
     
    class ManagerService(rpyc.Service):
        def exposed_foo(self, foo):
            logging.debug("manager got " + str(foo)) 
            return
     
    class Manager:
        def __init__(self, addr):
            self.node = rpyc.connect(addr.host, addr.mport, service = ManagerService, config=RPYC_CFG)
     
    if __name__ == "__main__":
        addr = netAddr("localhost", 10000)
        n = Node(addr)
        m = Manager(addr)
        time.sleep(0.1) #give the node and manager some time to get acquainted
        n.manager.root.foo("bar2")
```

 
 
log output:

  ```
  2020-03-29 18:03:29 INFO     server started on [127.0.0.1]:10000
    2020-03-29 18:03:29 INFO     accepted ('127.0.0.1', 53007) with fd 756
    2020-03-29 18:03:29 INFO     welcome ('127.0.0.1', 53007)
```

 
console output:

```
     Traceback (most recent call last):
      File "c:/Users/ShaiDeshe/dev/pocs/ghostdag/netsim/isolated.py", line 54, in <module>
        n.manager.root.foo("bar2")
      File "C:\Users\ShaiDeshe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rpyc\core\protocol.py", line 502, in root        
        self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
      File "C:\Users\ShaiDeshe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rpyc\core\protocol.py", line 469, in sync_request
        return self.async_request(handler, *args, timeout=timeout).value
      File "C:\Users\ShaiDeshe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rpyc\core\async_.py", line 100, in value
        self.wait()
      File "C:\Users\ShaiDeshe\AppData\Local\Programs\Python\Python38-32\lib\site-packages\rpyc\core\async_.py", line 49, in wait
        raise AsyncResultTimeout("result expired")
    TimeoutError: result expired
```

**Comment by comrumino** [comment]
I would start with 
```
import rpyc, sys, threading, time, socket, random
from rpyc.utils.server import ThreadedServer
from rpyc.lib import setup_logger
import pathlib
currentdir = pathlib.Path(__file__).resolve()
parentdir = currentdir.parent
sys.path.insert(0, parentdir)
from dag import DAG
import logging
import copy


class cfg(object):
    host = "localhost"
    port = 10000
    rpyc_proto = {"allow_all_attrs": True, "allow_pickle": True, "logger": setup_logger()}


class FeeFie(object):
    def __init__(self, initial_value="fee"):
        self.value = initial_value

    def __str__(self):
        return f"{self.value} fie"


class ManagerService(rpyc.Service):
    def __init__(self):
        self.fee_fie = FeeFie()

    def exposed_foe(self, foo, bar):
        return f"{self.fee_fie} foe {foo} {bar}"

 
if __name__ == "__main__":
    # start server
    server = ThreadedServer(ManagerService, hostname=cfg.host, port=cfg.port, protocol_config=cfg.rpyc_proto)
    server.logger.quiet = False
    server_thread = server._start_in_thread()
    # start client
    client = rpyc.connect(cfg.host, cfg.port, service=ManagerService, config=cfg.rpyc_proto)
    immutable_value = client.root.foe(foo="foo", bar="bar")
    print(f"my immutable value: {immutable_value}")
```
Then add small increments of functionality and test each addition. I'm not sure where the implementation issue is in your code. But, it is easier to have a known working point to start.

**Comment by kylesjtu** [comment]
I've come across the same problem today. I found that the call of service's connection is blocked and it would run after client call service method for 2 times. So i guess the author use some signal to block when using decoupling services. Anyway,I found one solution, which is  using rpyc.BgServingThread, which means adding this line:
```
def on_connect(self, conn):
            self.node.manager = conn
            bg_server = BgServingThread(conn) 
            #don't work either:
            #conn.root.foo("bar0")
            #self.node.manager.root.foo("bar1")
```
  Hope this works for others.
