### ISSUE TITLE
Attempt to execute a teleported function on remote host with different Python version results in SystemError: Unknown opcode

### ISSUE THREAD

**Issue by tmp6154** [tomerfiliba/rpyc#387]
Hello! I'm just getting started with RPyC library, using classic mode and I've attempted to **teleport** a simple function to execute on remote host. My server has a different Python version than client. Documentation isn't clear, whether there's any limitations on Python version regarding function teleportation, and looking at code in _teleportation.py_, I can assume this scenario is supported and it should even work on different OSes, so this looks like a bug.
  
```                                                                           
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
<ipython-input-19-1f2268e10ba7> in <module>
----> 1 r('/download.py', '')

/usr/lib/python3.7/site-packages/rpyc/core/netref.py in __call__(_self, *args, **kwargs)
    251         def __call__(_self, *args, **kwargs):
    252             kwargs = tuple(kwargs.items())
--> 253             return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
    254         __call__.__doc__ = doc
    255         return __call__

/usr/lib/python3.7/site-packages/rpyc/core/netref.py in syncreq(proxy, handler, *args)
     74     """
     75     conn = object.__getattribute__(proxy, "____conn__")
---> 76     return conn.sync_request(handler, proxy, *args)
     77 
     78 

/usr/lib/python3.7/site-packages/rpyc/core/protocol.py in sync_request(self, handler, *args)
    467         """
    468         timeout = self._config["sync_request_timeout"]
--> 469         return self.async_request(handler, *args, timeout=timeout).value
    470 
    471     def _async_request(self, handler, args=(), callback=(lambda a, b: None)):  # serving

/usr/lib/python3.7/site-packages/rpyc/core/async_.py in value(self)
    100         self.wait()
    101         if self._is_exc:
--> 102             raise self._obj
    103         else:
    104             return self._obj

SystemError: unknown opcode

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/root/tmp.Q3FMlTXe62/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/root/tmp.Q3FMlTXe62/rpyc/core/protocol.py", line 593, in _handle_call
    return obj(*args, **dict(kwargs))
  File "<ipython-input-17-df17b43e7680>", line 3, in calcMd5
SystemError: unknown opcode
```

##### Environment

RPyC 4.1.4 (Using zero-deploy, so both sides have same version)

Server Python: 3.6.6 (default, Mar 10 2019, 13:45:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)
Client Python: 3.7.7 (default, May 17 2020, 22:21:12) [GCC 9.3.0] + ipython3

Server OS: CentOS 7
Client OS: Gentoo Linux

##### Minimal example

Server:

Connection is established via Paramiko.

```
from plumbum.machines.paramiko_machine import ParamikoMachine                                                   

from rpyc.utils.zerodeploy import DeployedServer 

from paramiko.client import AutoAddPolicy 

mach = ParamikoMachine("myserver", user="user", password="password", load_system_host_keys=False, missing_host_policy=AutoAddPolicy)                                                                                       

server = DeployedServer(mach)                                                                                  

conn = server.classic_connect()
```

Then I define a simple file MD5 calculation function that I want to run on remote host.

```
def calcMd5(file_name, prefix): 
    import hashlib 
    md5obj = hashlib.md5(prefix.encode('utf-8')) 
    with open(file_name, 'rb') as f: 
        chunk_size = 1 << 20 
        while 1: 
            s = f.read(chunk_size) 
            if not s: 
                break 
            md5obj.update(s) 
    return md5obj.hexdigest()                                                                                                                

r = conn.teleport(calcMd5)                          
```                                                           

Then, attempting to invoke teleported function results in SystemError: Unknown opcode on remote:

In [19]: r('/download.py', '')             

This yields an above stack track about unknown opcode. Still, simpler functions work perfectly.

```
In [8]: r = conn.teleport(lambda x: x**2)                                                                               

In [9]: r(2)                                                                                                            
Out[9]: 4
```

**Comment by Jongy** [comment]
It's not strictly forbidden, but unless you are very wary of what you're teleporting, I wouldn't suggest you to do it.

Teleportation sends the bytecode as-is, and the bytecode format might go through big changes across Python minor versions.
For example, between Python 3.7 and 3.8, the opcode sequence for a `for` loop has changed completely (so teleporting code with `for` won't work 3.7 <-> 3.8).

I've used teleportation of 3.7 -> 3.8 in one of my projects (see #370 I added) but I had to be very careful with teleported code. Eventually I got tired of those occasional `SystemError`s and the need to get around them, so I downgraded the 3.8 to 3.7 to make them match :sweat_smile: If both Python versions are of the same minor, it'll be okay (AFAIK bytecode doesn't change in the same minor)

**Comment by tmp6154** [comment]
@Jongy Yes, you're right. I've ended up with source-level workaround to achieve "teleporting" of functions between the hosts, since in my project it's very difficult to achieve Python version parity, which indeed should've resolved the issue.

I just get the source of the required function via inspect module, send it to remote host, and then evaluate it there. So, effect is essentially same - you have "teleported" a function from one host to another, except that it works across all Python 3.x versions (as long as you don't use something not supported in one of your target Python versions). Since each function is evaluated and compiled to bytecode by exact same interpreter that's going to run it - this completely lifts bytecode compatibility constraints from teleportation.

**Comment by Jongy** [comment]
That's a cool workaround!

Regarding RPyC, I believe this constraint should be added to the documentation, because as you said, it's not mentioned anywhere and experiencing `SystemError`s is not very user-friendly.

**Comment by comrumino** [comment]
When attempting to teleport to a function for a Windows client to a Linux server, a segmentation fault server side and a EOFError thrown on the client side. The issue reported in #424 is a duplicate of this issue.

**Comment by kaphola** [comment]
> @Jongy Yes, you're right. I've ended up with source-level workaround to achieve "teleporting" of functions between the hosts, since in my project it's very difficult to achieve Python version parity, which indeed should've resolved the issue.
> 
> I just get the source of the required function via inspect module, send it to remote host, and then evaluate it there. So, effect is essentially same - you have "teleported" a function from one host to another, except that it works across all Python 3.x versions (as long as you don't use something not supported in one of your target Python versions). Since each function is evaluated and compiled to bytecode by exact same interpreter that's going to run it - this completely lifts bytecode compatibility constraints from teleportation.

@tmp6154 Even i am facing the same issue, would it be possible for you to share code snippet for the workaround. Thanks

**Comment by comrumino** [comment]
@kaphola 
```
def new_conditions():
    conn = rpyc.classic.connect('rpyc-3.10', 18812)
    src = inspect.getsource(new_calcMd5)
    conn.execute("import hashlib")
    conn.execute(src)
    netref_new_calcMd5 = conn.namespace[new_calcMd5.__name__]
    netref_new_calcMd5('/opt/rpyc/rpyc/version.py', 'test-opcode')
    print(netref_new_calcMd5('/opt/rpyc/rpyc/version.py', 'test-opcode')
```
I tested it and the resolve opcode errors. This isn't a bullet proof solution. I'll continue looking into it.

**Comment by tmp6154** [comment]
Yeah, something like that. With some work, it's even possible to make it a decorator to allow removing some boilerplate and "teleport" various functions with just adding a decorator (e.g. @remote_call), but how to implement it hightly depends on the project and which object(s) handles connection object. But yes, it would be not a bullet proof solution (there's a lot that could go wrong, especially decorators could be a problem).
