### ISSUE TITLE
getarrt on netref causes excpetion-message at server-log

### ISSUE THREAD

**Issue by walterschneider** [tomerfiliba/rpyc#395]
When calling getattr with a non-existing attribute on a netref object, the server prints an exception message.
We're using copy.deepcopy() on remote obejcts to improve speed when iterating over a netref list-object;
deepcopy is using getattr(obj, "__deepcopy__", None) to determine if an object provides it's own deepcopy method.

As well as this has no effect on the functionality, the exception-message in the server-log is a little bit nasty here.

```
DEBUG:SLAVE/18812:Exception caught
Traceback (most recent call last):
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 612, in _handle_getattr
    return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 540, in _access_attr
    return accessor(obj, name, *args)
AttributeError: 'list' object has no attribute '__deepcopy__'
DEBUG:SLAVE/18812:Exception caught
Traceback (most recent call last):
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 612, in _handle_getattr
    return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/home/wasc/.local/lib/python3.6/site-packages/rpyc/core/protocol.py", line 540, in _access_attr
    return accessor(obj, name, *args)
AttributeError: 'list' object has no attribute '__deepcopy__'

```

##### Environment

- rpyc 4.1.5
- python 3.6
- operating system: ubuntu 18.04

##### Minimal example

Server:

```bash
rpyc_classic.py
```

Client:

```python
import rpyc


if __name__ == "__main__":
    conn = rpyc.classic.connect("localhost")
    conn.execute("a=[]")
    ra=conn.namespace["a"]
    getattr(ra,"__deepcopy__", None)
```

**Comment by walterschneider** [comment]
What about supressing the logging for AttributeError?

```diff
diff --git a/rpyc/core/protocol.py b/rpyc/core/protocol.py
index be0354c..e530ed2 100644
--- a/rpyc/core/protocol.py
+++ b/rpyc/core/protocol.py
@@ -323,7 +323,7 @@ class Connection(object):
             t, v, tb = sys.exc_info()
             self._last_traceback = tb
             logger = self._config["logger"]
-            if logger and t is not StopIteration:
+            if logger and t is not StopIteration and t is not AttributeError:
                 logger.debug("Exception caught", exc_info=True)
             if t is SystemExit and self._config["propagate_SystemExit_locally"]:
                 raise
```

**Comment by sergeyyatmellanox** [comment]
As I understand, list created "remotely" are not actual lists locally(and vise-versa).
I had the same issue. I was forced to cast the lists again.
Instead of : remote_list + local_list.
I do: list(remote_list) + local_list.

**Comment by comrumino** [comment]
> What about supressing the logging for AttributeError?

Technically the exception is valid since `getattr(list(),"__deepcopy__")` locally results in an exception. However, the behavior should provide the default of `None` in place of the exception. The proper fix here would be to better handle the default behavior of `getattr(list(),"__deepcopy__", None)` when the attribute doesn't exist.
